-- =====================================================================
-- Migracao 01 - variacoes de produto (sabor / tamanho)
-- Rodar UMA VEZ no SQL Editor do Supabase, depois do schema.sql e do seed.sql.
-- E idempotente: pode rodar de novo sem quebrar nada.
--
-- O que faz:
--   1. cria as colunas grupo / linha / tamanho em produto
--   2. preenche as tres para os 761 SKUs e padroniza a grafia dos sabores
--   3. desativa o SKU que a NE cadastrou duplicado
--   4. recria produto_publico com as colunas novas
--   5. cria a view vitrine: uma linha por grupo, para as listagens
-- =====================================================================
begin;

alter table produto add column if not exists grupo   text;
alter table produto add column if not exists linha   text;
alter table produto add column if not exists tamanho text;

create index if not exists produto_grupo_idx on produto (grupo) where ativo;

-- ---------------------------------------------------------------------
-- 2. preenchimento
-- ---------------------------------------------------------------------
update produto p set
  grupo   = v.grupo,
  linha   = v.linha,
  tamanho = v.tamanho,
  sabor   = v.sabor
from (values
('12860','vitafor--isofort-wpi','Isofort WPI','Display 15 un 30g','Neutro'),
('12859','canibal-inc--sweet-hydro-protein','Sweet Hydro Protein','Pote 900g','Limonada Suiça'),
('12858','canibal-inc--sweet-hydro-protein','Sweet Hydro Protein','Pote 900g','Melancia'),
('12847','dux--whey-protein-concentrado','Whey Protein Concentrado','Pote 900g','Caramelo Salgado'),
('12840','trustfuel--whey-powerfuel-protein','Whey Powerfuel Protein','900g','Chocolate'),
('12839','trustfuel--powerfuel-protein-uht','Powerfuel Protein Uht','250ml','Morango'),
('12838','trustfuel--whey-powerfuel-protein','Whey Powerfuel Protein','900g','Coco'),
('12837','trustfuel--whey-powerfuel-protein','Whey Powerfuel Protein','900g','Baunilha'),
('12832','uevo--recovery','Recovery','Saco 1kg','Morango'),
('12831','uevo--albumina','Albumina','Saco 420g','Cocada Cremosa'),
('12830','uevo--albumina','Albumina','Saco 420g','Caramelo Salgado'),
('12820','integralmedica--whey-100-pure','Whey 100% Pure','Display 10 un 20g','Cookies'),
('12813','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Chocolate Branco'),
('12808','nutrata--whey-beef-protein','Whey Beef Protein','Pote 900g','Frutas Tropicais'),
('12807','nutrata--whey-beef-protein','Whey Beef Protein','Pote 900g','Frutas Citricas'),
('12806','nutrata--whey-beef-protein','Whey Beef Protein','Pote 900g','Frutas Roxas'),
('12800','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Banana'),
('12789','atlhetica-nutrition--100-whey-flavour','100% Whey Flavour','Refil 900g','Chocolate'),
('12788','atlhetica-nutrition--100-whey-flavour','100% Whey Flavour','Refil 900g','Leite'),
('12787','atlhetica--carnitech-beef-protein','Carnitech Beef Protein','Pote 840g','Lemon Ice'),
('12786','atlhetica--carnitech-beef-protein','Carnitech Beef Protein','Pote 840g','Cookies and Cream'),
('12785','atlhetica--carnitech-beef-protein','Carnitech Beef Protein','Pote 840g','Morango'),
('12784','atlhetica--carnitech-beef-protein','Carnitech Beef Protein','Pote 840g','Chocolate'),
('12783','atlhetica--carnitech-beef-protein','Carnitech Beef Protein','Pote 840g','Vanilla Caramel'),
('12741','us-nutrition--100-whey','100% Whey','Pote 900g','Cookies'),
('12738','us-nutrition--100-whey','100% Whey','Pote 900g','Chocolate Belga'),
('12737','us-nutrition--100-whey','100% Whey','Pote 900g','Morango'),
('12736','us-nutrition--100-whey','100% Whey','Pote 900g','Leite Ninho'),
('12735','us-nutrition--100-whey','100% Whey','Pote 900g','Ovo Maltine'),
('12734','us-nutrition--100-whey','100% Whey','Pote 900g','Baunilha'),
('12726','us-nutrition--power-whey','Power Whey','Pote 900g','Chocolate Belga'),
('12724','us-nutrition--power-whey','Power Whey','Pote 900g','Leitinho'),
('12698','canibal-inc--sweet-hydro-protein','Sweet Hydro Protein','Pote 900g','Manga com Pessego'),
('12641','uevo--albumina','Albumina','Saco 420g','Banoffee'),
('12633','uevo--albumina','Albumina','Saco 1kg','Banoffee'),
('12548','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Caramelo Salgado'),
('12535','integralmedica--whey-100-pure','Whey 100% Pure','Display 10 un 20g','Chocolate'),
('12534','integralmedica--whey-100-pure','Whey 100% Pure','Display 10 un 20g','Baunilha'),
('12504','shark-pro--whey-beef-protein-display-10-saches','Whey Beef Protein - Display 10 Sachês','35g','Abacaxi com Hortelã'),
('12503','shark-pro--whey-protein-joypro-display-10-saches','Whey Protein Joypro - Display 10 Sachês','33g','Brigadeiro'),
('12499','shark-pro--whey-protein-joypro-display-10-saches','Whey Protein Joypro - Display 10 Sachês','33g','Cookies de Banana com Canela'),
('12496','shark-pro--whey-beef-protein-display-10-saches','Whey Beef Protein - Display 10 Sachês','35g','Morango com Maracujá'),
('12486','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Abacaxi com Hortelã'),
('12484','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Melancia com Limão'),
('12479','canibal-inc--sweet-hydro-protein','Sweet Hydro Protein','Pote 900g','Abacaxi com Hortelã'),
('12476','shark-pro--whey-beef-protein-display-10-saches','Whey Beef Protein - Display 10 Sachês','35g','Laranja com Acerola'),
('12474','shark-pro--whey-protein-joypro-display-10-saches','Whey Protein Joypro - Display 10 Sachês','33g','Iogurte Morango com Framboesa'),
('12473','shark-pro--whey-protein-joypro','Whey Protein Joypro','Pote 900g','Leite'),
('12468','trustfuel--goalmy-protein-90-gomas','Goalmy Protein 90 Gomas',null,'Baunilha'),
('12465','trustfuel--powerfuel-protein-uht','Powerfuel Protein Uht','250ml','Cookiescream'),
('12457','trustfuel--goalmy-protein-90-gomas','Goalmy Protein 90 Gomas',null,'Chocolate'),
('12454','trustfuel--powerfuel-protein','Powerfuel Protein','450g','Baunilha'),
('12453','trustfuel--powerfuel-protein','Powerfuel Protein','450g','Chocolate'),
('12452','trustfuel--powerfuel-protein','Powerfuel Protein','450g','Coco'),
('12451','trustfuel--powerfuel-protein-uht','Powerfuel Protein Uht','250ml','Chocolate'),
('12450','trustfuel--powerfuel-protein-uht','Powerfuel Protein Uht','250ml','Coco'),
('12415','ta-suplementos--wheycrea','Wheycrea','Pote 900g','Torta de Chocolate'),
('12414','ta-suplementos--wheycrea','Wheycrea','Pote 900g','Torta de Morango'),
('12413','ta-suplementos--wheycrea','Wheycrea','Pote 900g','Chocoleite'),
('12412','ta-suplementos--wheycrea','Wheycrea','Pote 900g','Cookiesmaltine'),
('12391','canibal-inc--gods-whey-100','Gods Whey 100%','Refil 900g','Chocolate'),
('12390','canibal-inc--gods-whey-100','Gods Whey 100%','Refil 900g','Baunilha'),
('12389','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Morango'),
('12388','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Baunilha'),
('12387','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Leite'),
('12386','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Cookies'),
('12385','canibal-inc--caniblend-protein','Caniblend Protein','Refil 900g','Chocolate'),
('12383','canibal-inc--gods-whey-100','Gods Whey 100%','Refil 900g','Morango'),
('12380','vitafor--whey-wpc-pouch','Whey WPC Pouch','Pote 900g','Baunilha'),
('12379','vitafor--whey-wpc-pouch','Whey WPC Pouch','Pote 900g','Beijinho'),
('12378','vitafor--whey-wpc-pouch','Whey WPC Pouch','Pote 900g','Morango'),
('12377','vitafor--whey-wpc-pouch','Whey WPC Pouch','Pote 900g','Mousse de Maracujá'),
('12375','dux--whey-protein-concentrado','Whey Protein Concentrado','Pote 900g','Cappuccino'),
('12366','pro-nutri--100-whey-protein','100% Whey Protein','Saco 900g','Leite em Pó'),
('12365','pro-nutri--100-whey-protein','100% Whey Protein','Saco 900g','Leite em Pó e Morango'),
('12364','ta-suplementos--wheycrea','Wheycrea','Pote 900g','Mousse de Baunilha'),
('12363','ta-suplementos--wheycrea','Wheycrea','Pote 900g','Brigadeiro Branco'),
('12360','uniao-vegetal--pure-whey-protein-display-12-saches','Pure Whey Protein - Display 12 Sachês','30g','Malte Crocante'),
('12356','vitafor--isocrisp-plant','Isocrisp Plant','Pote 60g',null),
('12345','vitafor--isocrisp','Isocrisp','Pote 60g','Neutro'),
('12344','vitafor--isocrisp-plant','Isocrisp Plant','Pouch 240g',null),
('12343','vitafor--isocrisp-whey-pote-neutro-pouch','Isocrisp Whey - Pote Neutro Pouch','240g',null),
('12331','vitafor--isofort-ultra-imuno','Isofort Ultra Imuno','Pote 900g','Cacau'),
('12326','vitafor--isofort-wpi','Isofort WPI','Display 15 un 30g','Baunilha'),
('12325','vitafor--isofort-wpi','Isofort WPI','Display 15 un 30g','Chocolate'),
('12324','vitafor--isofort-wpi','Isofort WPI','Display 15 un 30g','Frutas Vermelhas'),
('12323','vitafor--isofort-ultra-imuno','Isofort Ultra Imuno','Pote 900g','Baunilha'),
('12296','atlhetica-nutrition--best-whey','Best Whey','Display 15 un 40g','Milkshake Morango Bobs'),
('12293','ta-suplementos--whey-zero-leite-tres-sensacoes','Whey Zero Leite - Três Sensações','Pote 900g',null),
('12292','ta-suplementos--whey-zero-leite','Whey Zero Leite','Pote 900g','Sorvete de Doce de Leite'),
('12287','ta-suplementos--whey-zero-leite','Whey Zero Leite','Pote 900g','Coffee Caramel'),
('12279','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Milkshake Morango Bobs'),
('12252','ta-suplementos--carnbull','Carnbull','Pote 900g','Maçã Verde'),
('12231','ta-suplementos--carnbull','Carnbull','Pote 900g','Uva'),
('12228','shark-pro--whey-protein-joypro','Whey Protein Joypro','Refil 900g','Paçoca'),
('12225','shark-pro--whey-protein-joypro','Whey Protein Joypro','Refil 900g','Cookies Banana com Canela'),
('12221','max-titanium--100-whey-double-tasty','100% Whey Double Tasty','Pote 900g','Morango'),
('12220','bold-snacks--bold-whey','Bold Whey','Display 10 un 30g','Doce de Leite'),
('12212','ta-suplementos--carnbull','Carnbull','Pote 900g','Limonada Suiça'),
('12153','shark-pro--whey-protein-joypro','Whey Protein Joypro','Pote 900g','Brigadeiro'),
('12152','shark-pro--whey-protein-joypro','Whey Protein Joypro','Pote 900g','Cookies Banana com Canela'),
('12151','shark-pro--whey-protein-joypro','Whey Protein Joypro','Pote 900g','Iogurte Morango com Framboesa'),
('12150','shark-pro--whey-protein-joypro','Whey Protein Joypro','Pote 900g','Paçoca'),
('12019','new-millen--isolate-protein','Isolate Protein','Pote 900g','Abacaxi com Hortelã'),
('12018','new-millen--isolate-protein','Isolate Protein','Pote 900g','Orange Juice'),
('11951','ta-suplementos--whey-blend-3w-saco-1-8kg-400g-gratis','Whey Blend 3w - Saco 1.8kg + 400g Gratis','1.8kg','Milkshake de Baunilha'),
('11885','nutrata--w100-whey-display-12-saches','W100 Whey - Display 12 Sachês','30g','Morango'),
('11884','nutrata--w100-whey-display-12-saches','W100 Whey - Display 12 Sachês','30g','Creme de Baunilha'),
('11883','nutrata--w100-whey-display-12-saches','W100 Whey - Display 12 Sachês','30g','Duplo Chocolate'),
('11882','nutrata--w100-whey-display-12-saches','W100 Whey - Display 12 Sachês','30g','Cookies e Cream'),
('11881','nutrata--w100-whey-havanna-display-12-saches','W100 Whey Havanna - Display 12 Sachês','20g','Doce de Leite'),
('11861','uevo--albumina','Albumina','Saco 420g','Cafe Mocaccino'),
('11860','uevo--albumina','Albumina','Saco 1kg','Cafe Mocaccino'),
('11808','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Baunilha'),
('11807','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Morango'),
('11806','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Cookies e Cream'),
('11804','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Iogurte com Limão'),
('11803','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Iogurte com Morango'),
('11799','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Morango Kiwi'),
('11798','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Morango com Maracujá'),
('11797','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Frutas Roxas'),
('11796','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Laranja com Acerola'),
('11795','shark-pro--whey-beef-protein','Whey Beef Protein','Pote 900g','Frutas Tropicais'),
('11729','bold-snacks--bold-whey','Bold Whey','Display 10 un 30g','Cookies e Cream'),
('11726','bold-snacks--bold-whey','Bold Whey','Display 10 un 30g','Mousse de Morango'),
('11696','nutrata--whey-w100','Whey W100','Refil 900g','Cookies'),
('11695','nutrata--whey-w100','Whey W100','Refil 900g','Creme de Coco'),
('11680','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 37g','Pistache & Original'),
('11679','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Pistache & Original'),
('10979','atlhetica-nutrition--pure-blend-100-protein-lacto-free-refil','Pure Blend 100% Protein Lacto-free - Refil','1.814kg','Baunilha'),
('10978','atlhetica-nutrition--pure-blend-100-protein-lacto-free-refil','Pure Blend 100% Protein Lacto-free - Refil','1.814kg','Chocolate'),
('10963','atlhetica-nutrition--pure-blend-100-protein-lacto-free','Pure Blend 100% Protein Lacto-free','Refil 907g','Baunilha'),
('10962','atlhetica-nutrition--pure-blend-100-protein-lacto-free','Pure Blend 100% Protein Lacto-free','Refil 907g','Chocolate'),
('10961','atlhetica-nutrition--pure-blend-100-protein-lacto-free','Pure Blend 100% Protein Lacto-free','Refil 907g','Creme de Avelã'),
('10952','darkness--carnibol','Carnibol','Pote 900g','Baunilha'),
('10487','naturovos--albumina','Albumina','Saco 420g','Natural'),
('10486','uevo--albumina','Albumina','Saco 1kg','Chocolate'),
('10485','uevo--albumina','Albumina','Saco 1kg','Morango'),
('10484','uevo--albumina','Albumina','Saco 1kg','Baunilha'),
('10483','uevo--albumina','Albumina','Saco 420g','Chocolate'),
('10482','uevo--albumina','Albumina','Saco 420g','Morango'),
('10481','uevo--albumina','Albumina','Saco 420g','Baunilha'),
('10480','naturovos--albumina','Albumina','Saco 1kg','Natural'),
('10332','pro-nutri--100-whey-protein','100% Whey Protein','Saco 900g','Milkshake de Baunilha'),
('10330','pro-nutri--100-whey-protein','100% Whey Protein','Saco 900g','Chocolate'),
('10145','integralmedica--whey-100-pure','Whey 100% Pure','Refil 900g','Gelato Di Latte'),
('9991','ta-suplementos--whey-zero-leite','Whey Zero Leite','Pote 900g','Sorvete de Morango'),
('9990','ta-suplementos--whey-zero-leite','Whey Zero Leite','Pote 900g','Sorvete de Chocolate'),
('9877','atlhetica-nutrition--best-whey-toddy-achocolatado','Best Whey Toddy - Achocolatado','Pote 450g',null),
('9876','atlhetica-nutrition--best-whey-achocolatado-toddy','Best Whey - Achocolatado Toddy','Display 15 sachês 40g',null),
('9875','atlhetica-nutrition--best-whey-toddy-achocolatado','Best Whey - Toddy Achocolatado','Pote 900g',null),
('9287','proforce--muscle-whey-3w','Muscle Whey 3w','Saco 2kg','Chocolate'),
('9281','proforce--muscle-whey-3w','Muscle Whey 3w','Saco 2kg','Morango'),
('8560','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 40g','Brownie Chocolate'),
('8557','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 40g','Leite, Cacau e Avelã'),
('8555','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 40g','Double Chocolate'),
('8553','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 35g','Vanilla Cream'),
('8510','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 40g','Brigadeiro Gourmet'),
('8459','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 37g','Chocolate Branco'),
('7345','shark-pro--100-whey-protein','100% Whey Protein','Refil 900g','Chocolate'),
('6690','bodyaction--100-whey-prime','100% Whey Prime','Pote 900g','Baunilha'),
('6689','bodyaction--100-whey-prime','100% Whey Prime','Pote 900g','Chocolate'),
('6688','bodyaction--100-whey-prime','100% Whey Prime','Pote 900g','Morango'),
('6665','probiotica--100-pure-whey','100% Pure Whey','Refil 900g','Iogurte com Coco'),
('6532','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Brigadeiro Gourmet'),
('6357','atlhetica-nutrition--100-whey-flavour','100% Whey Flavour','Refil 900g','Chocolate'),
('6168','atlhetica-nutrition--best-whey','Best Whey','Display 15 sachês 35g','Dulce de Leche Premium'),
('6161','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Dulce de Leche Premium'),
('6056','probiotica--100-pure-whey','100% Pure Whey','Refil 900g','Cookies e Cream'),
('5813','probiotica--100-pure-whey','100% Pure Whey','Refil 900g','Iogurte com Morango'),
('5807','nutrata--whey-w100','Whey W100','Pote 900g','Creme de Coco'),
('5804','nutrata--whey-w100','Whey W100','Pote 900g','Chocolate'),
('5044','atlhetica-nutrition--best-vegan','Best Vegan','Pote 500g','Cacau'),
('3949','bodyaction--isolate-definition-refil','Isolate Definition - Refil','1.8kg','Morango'),
('3948','bodyaction--isolate-definition-refil','Isolate Definition - Refil','1.8kg','Baunilha'),
('3947','bodyaction--isolate-definition-refil','Isolate Definition - Refil','1.8kg','Chocolate'),
('3912','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Chocomaltine'),
('3379','pure-suplementos--pure-whey-concentrado','Pure Whey Concentrado','Pote 1kg','Coco'),
('3341','probiotica--100-pure-whey','100% Pure Whey','Pote 900g','Chocolate'),
('2137','bodyaction--isolate-prime-whey','Isolate Prime Whey','Pote 900g','Baunilha'),
('2133','bodyaction--isolate-prime-whey','Isolate Prime Whey','Pote 900g','Chocolate'),
('2125','bodyaction--isolate-definition','Isolate Definition','Pote 900g','Morango'),
('2123','bodyaction--isolate-definition','Isolate Definition','Pote 900g','Baunilha'),
('2122','bodyaction--3-whey-top-taste','3 Whey Top Taste','Pote 900g','Morango'),
('1785','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Condensed Milk'),
('1738','vitafor--whey-fort-3w','Whey Fort 3w','Pote 900g','Frutas Vermelhas'),
('1736','vitafor--whey-fort-3w','Whey Fort 3w','Pote 900g','Chocolate'),
('1732','vitafor--whey-fort-3w','Whey Fort 3w','Pote 900g','Neutro'),
('1683','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Dulce de Leche'),
('1682','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Chocotella Cream'),
('1681','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Vanilla Cream'),
('1680','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Chocolate Suiço'),
('1678','adaptogen--tasty-whey-3w','Tasty Whey 3w','Pote 900g','Strawberry Cream'),
('1667','vitafor--isofort-plant','Isofort Plant','Pote 450g','Cacau'),
('1666','atlhetica-nutrition--best-whey-iso','Best Whey ISO','Pote 900g','Brigadeiro'),
('1665','atlhetica-nutrition--best-whey-iso','Best Whey ISO','Pote 900g','Baunilha'),
('1634','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Cookies e Cream'),
('1622','atlhetica-nutrition--best-vegan','Best Vegan','Pote 500g','Original'),
('1618','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Original'),
('1616','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Double Chocolate'),
('1615','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Vanilla Cream'),
('1611','atlhetica-nutrition--best-whey','Best Whey','Pote 900g','Leite, Cacau e Avelã'),
('1566','vitafor--whey-fort-3w','Whey Fort 3w','Pote 900g','Baunilha'),
('1553','vitafor--isofort-plant','Isofort Plant','Pote 450g','Banana com Canela'),
('1520','bodyaction--100-whey-prime','100% Whey Prime','Refil 900g','Chocolate'),
('1492','max-titanium--100-whey','100% Whey','Refil 900g','Chocolate'),
('1490','max-titanium--100-whey','100% Whey','Refil 900g','Morango'),
('1489','max-titanium--100-whey','100% Whey','Refil 900g','Baunilha'),
('1454','max-titanium--100-whey','100% Whey','Pote 900g','Cookies e Cream'),
('1446','integralmedica--whey-100-pure','Whey 100% Pure','Refil 900g','Cookies and Cream'),
('1445','integralmedica--whey-100-pure','Whey 100% Pure','Refil 900g','Baunilha'),
('1444','integralmedica--whey-100-pure','Whey 100% Pure','Refil 900g','Chocolate'),
('1442','dux--whey-protein-concentrado','Whey Protein Concentrado','Pote 900g','Coco'),
('1425','bodyaction--isolate-prime-whey','Isolate Prime Whey','Pote 900g','Morango'),
('1404','dux--whey-protein-concentrado','Whey Protein Concentrado','Pote 900g','Baunilha'),
('1402','vitafor--isofort-plant','Isofort Plant','Pote 450g','Baunilha'),
('1371','max-titanium--top-whey-3w-performance','Top Whey 3w + Performance','Pote 900g','Morango'),
('1369','max-titanium--top-whey-3w-performance','Top Whey 3w + Performance','Pote 900g','Chocolate'),
('1368','max-titanium--top-whey-3w-performance','Top Whey 3w + Performance','Pote 900g','Baunilha'),
('1345','vitafor--isofort','Isofort','Pote 900g','Neutro'),
('1344','vitafor--isofort','Isofort','Pote 900g','Frutas Vermelhas'),
('1343','vitafor--isofort','Isofort','Pote 900g','Chocolate'),
('1342','vitafor--isofort','Isofort','Pote 900g','Baunilha'),
('1339','darkness--carnibol','Carnibol','Pote 900g','Salt Caramelo'),
('1338','darkness--carnibol','Carnibol','Pote 900g','Chocolate'),
('1320','bodyaction--3-whey-top-taste','3 Whey Top Taste','Pote 900g','Chocolate'),
('1319','bodyaction--3-whey-top-taste','3 Whey Top Taste','Pote 900g','Baunilha'),
('1318','probiotica--100-pure-whey','100% Pure Whey','Refil 900g','Morango'),
('1317','probiotica--100-pure-whey','100% Pure Whey','Refil 900g','Chocolate'),
('1316','probiotica--100-pure-whey','100% Pure Whey','Refil 900g','Baunilha'),
('1315','max-titanium--100-whey','100% Whey','Pote 900g','Morango'),
('1314','max-titanium--100-whey','100% Whey','Pote 900g','Chocolate'),
('12856','shark-pro--mini-crunch-shark','Mini Crunch Shark','20g','Barras Sortidas'),
('12850','shark-pro--protein-bar-shark-crush','Protein Bar Shark Crush','Display 12 un 40g','Morango com Iorgute'),
('12849','shark-pro--protein-bar-shark-crush','Protein Bar Shark Crush','Display 12 un 40g','Marshmallow'),
('12848','shark-pro--protein-bar-shark-crush','Protein Bar Shark Crush','Display 12 un 40g','Brigadeiro'),
('12845','bendu--salgadinho-proteico-salty-chips','Salgadinho Proteico Salty Chips','40g','White Cheese'),
('12844','bendu--salgadinho-proteico-salty-chips','Salgadinho Proteico Salty Chips','40g','Sour Cream'),
('12843','canibal-inc--sweet-magic','Sweet Magic','Display 24 un 25g','Peanut Butter Crocante e Coco Cream'),
('12835','johnny--pipoca-do-johnny','Pipoca do Johnny','75g','Caramelo e Flor de Sal'),
('12834','johnny--pipoca-do-johnny','Pipoca do Johnny','75g','Brownie'),
('12829','uevo--pipoca','Pipoca','75g','Caramelo e Flor de Sal'),
('12828','johnny--pipoca-do-johnny','Pipoca do Johnny','40g','Sour Cream'),
('12818','irreal-snacks--chips-de-proteina','Chips de Proteina','40g','Paprica Picante'),
('12817','irreal-snacks--chips-de-proteina','Chips de Proteina','40g','Cebola Caramelizada'),
('12815','irreal-snacks--chips-de-proteina','Chips de Proteina','40g','White Cheddar'),
('12810','bold-snacks--bold-bar','Bold Bar','Display 12 un 40g','Trufa de Chocolate'),
('12801','canibal-inc--sweet-magic','Sweet Magic','Display 24 un 20g','Leitinho'),
('12796','canibal-inc--sweet-magic','Sweet Magic','Display 24 un 20g','Doce de Leite'),
('12762','supley--salgadinho-proteico','Salgadinho Proteico','40g','Cebola e Salsa'),
('12761','supley--salgadinho-proteico','Salgadinho Proteico','40g','Pesto e Parmesão'),
('12646','bendu--crispy-wafer','Crispy Wafer','Display 12 un 40g','Malte Chocolate'),
('12564','ta-suplementos--brigadeiro-mel-12-unidades','Brigadeiro Mel 12 Unidades',null,null),
('12562','nutrata--salgadinho-proteico-zig-fit','Salgadinho Proteico Zig Fit','40g','Lemon Pepper'),
('12561','nutrata--salgadinho-proteico-zig-fit','Salgadinho Proteico Zig Fit','40g','Dois Queijos'),
('12560','nutrata--salgadinho-proteico-zig-fit','Salgadinho Proteico Zig Fit','40g','Barbecue'),
('12517','supley--salgadinho-proteico','Salgadinho Proteico','40g','Cheeseburger'),
('12493','max-titanium--power-protein-crisp-bar','Power Protein Crisp Bar','Display 12 un 44g','Banoffee'),
('12492','max-titanium--power-protein-crisp-bar','Power Protein Crisp Bar','Display 12 un 44g','Cappuccino'),
('12481','canibal-inc--gods-wafer','Gods Wafer','Display 6 un 51g','Coco'),
('12480','canibal-inc--gods-wafer','Gods Wafer','Display 6 un 51g','Cookies e Cream'),
('12430','nutrata--yopro-bar','Yopro Bar','Display 12 un 55g','Cappuccino'),
('12429','nutrata--whey-grego-bar-havanna-zero','Whey Grego Bar Havanna Zero','Display 12 un 40g','Doce de Leite'),
('12369','bendu--sublime','Sublime','Display 10 un 40g','Baunilha'),
('12329','vitafor--snack-assado-fitzei','Snack Assado Fitzei','Saco 45g','Churrasco'),
('12320','nature-foodtech--barra-tamara-colageno-verisol','Barra Tamara + Colageno Verisol','Display 12 un 35g','Chocolate Meio Amargo'),
('12319','nature-foodtech--barra-tamara-colageno-verisol','Barra Tamara + Colageno Verisol','Display 12 un 35g','Morango'),
('12317','nature-foodtech--barra-tamara-creatina-creapure','Barra Tamara + Creatina Creapure','Display 12 un 35g','Chocolate Meio Amargo'),
('12316','nature-foodtech--barra-tamara-creatina-creapure','Barra Tamara + Creatina Creapure','Display 12 un 35g','Morango'),
('12314','nature-foodtech--barra-tamara-colageno-verisol','Barra Tamara + Colageno Verisol','Display 12 un 35g','Cookies and Cream'),
('12312','nutrata--protobar-charge-caramelo-amendoim-e-cobertura-de-chocolate','Protobar Charge - Caramelo Amendoim e Cobertura de Chocolate','Display 12 un 45g',null),
('12299','z2-foods--barz-mini-barra-energetica-z2','Barz Mini Barra Energetica Z2','Display 10 un 30g','Chocolate com Amendoim'),
('12298','z2-foods--barz-mini-barra-energetica-z2','Barz Mini Barra Energetica Z2','Display 10 un 30g','Bagas Limão Siciliano'),
('12229','nutrata--barra-nutrata-bacio-di-latte','Barra Nutrata Bacio Di Latte','Display 12 un 45g','Caramelo Salgado'),
('11853','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Salted Pão de Alho'),
('11850','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Morango'),
('11848','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Doce de Leite Argentino'),
('11846','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Cookies and Cream'),
('11843','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Salted Pepperoni'),
('11841','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Salted Marguerita'),
('11840','mrs-taste--taste-cookie-bar','Taste Cookie Bar','Display 12 un 50g','Speculoos Caramelo com Especiarias'),
('11822','bendu--soft-bar','Soft Bar','Display 12 un 45g','Dark Chocolate'),
('11819','probiotica--whey-bar-creamy','Whey Bar Creamy','Display 12 un 38g','Chocolate'),
('11732','bold-snacks--bold-bar','Bold Bar','Display 12 un 40g','Bombom Crocante'),
('11731','bold-snacks--bold-bar','Bold Bar','Display 12 un 40g','Cookies e Cream'),
('11730','bold-snacks--bold-bar','Bold Bar','Display 12 un 40g','Pistache'),
('11709','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Ovomaltine'),
('11697','nutrata--barra-nutrata-bacio-di-latte','Barra Nutrata Bacio Di Latte','Display 12 un 40g','Pistache'),
('11694','nutrata--yopro-bar','Yopro Bar','Display 12 un 55g','Morango com Chocolate Branco'),
('11678','atlhetica-nutrition--best-whey-bar-15g-protein','Best Whey Bar 15g Protein','Display 12 un 49g','Pistache & Original'),
('11677','bendu--crispy-wafer','Crispy Wafer','Display 12 un 40g','Dark Chocolate'),
('11673','bold-snacks--bold-crunch','Bold Crunch','Display 12 un 60g','Brigadeiro'),
('11672','bold-snacks--bold-crunch','Bold Crunch','Display 12 un 60g','Cookies e Cream'),
('11656','barrinhas-e-snacks--pacoca-whey-zero','Paçoca Whey Zero','20g','Natural Bendu'),
('11609','bendu--pacoca-zero','Paçoca Zero','Display 24 un 20g','Natural'),
('11608','bendu--pacoca-whey','Paçoca Whey','Display 24 un 20g','Cookies'),
('11607','bendu--pacoca-whey','Paçoca Whey','Display 24 un 20g','Leite em Pó'),
('11606','bendu--pacoca-whey','Paçoca Whey','Display 24 un 20g','Doce de Leite'),
('11605','bendu--pacoca-whey','Paçoca Whey','Display 24 un 20g','Cookie de Chocolate'),
('11601','bendu--sublime','Sublime','Display 10 un 40g','Avelã'),
('11600','bendu--sublime','Sublime','Display 10 un 40g','Doce de Leite'),
('11599','bendu--sublime','Sublime','Display 10 un 40g','Cookies'),
('11598','bendu--sublime','Sublime','Display 10 un 40g','Pistache'),
('11596','bendu--soft-bar','Soft Bar','Display 12 un 45g','Cookies'),
('11594','bendu--soft-bar','Soft Bar','Display 12 un 45g','Leite em Pó'),
('10972','dr-peanut--doctor-bar','Doctor Bar','Display 8 un 62g','Cookies e Cream'),
('10971','dr-peanut--doctor-bar','Doctor Bar','Display 8 un 62g','Doce de Leite'),
('10472','nutrata--yopro-bar','Yopro Bar','Display 12 un 55g','Chocolate'),
('10417','max-titanium--power-protein-crisp-bar','Power Protein Crisp Bar','Display 12 un 44g','Cookies'),
('10415','max-titanium--power-protein-crisp-bar','Power Protein Crisp Bar','Display 12 un 44g','Frutas Vermelhas'),
('10157','nutrata--whey-grego-bar-havanna','Whey Grego Bar Havanna','Display 12 un 40g','Brownie de Chocolate com Dulce de Leche'),
('10156','nutrata--whey-grego-bar-havanna','Whey Grego Bar Havanna','Display 12 un 40g','Banoffee com Dulce de Leche'),
('10134','atlhetica-nutrition--best-whey-protein-ball','Best Whey Protein Ball','Display 12 un 50g','Dulce de Leche Premium'),
('9996','bold-snacks--bold-bar','Bold Bar','Display 12 un 60g','Pistache'),
('9262','nutrata--barra-nutrata','Barra Nutrata','Display 12 un 45g','Caramel Protein'),
('9252','nutrata--barra-nutrata','Barra Nutrata','Display 12 un 45g','Dark Caramel Protein'),
('9223','shark-pro--salgadinho-proteico','Salgadinho Proteico','50g','Salsa e Cebola'),
('9222','shark-pro--salgadinho-proteico','Salgadinho Proteico','50g','Churrasco'),
('9221','shark-pro--salgadinho-proteico','Salgadinho Proteico','50g','Requeijao'),
('9073','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Creme de Coco'),
('8884','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Brownie de Chocolate'),
('8879','atlhetica-nutrition--best-whey-bar-15g-protein','Best Whey Bar 15g Protein','Display 12 un 62g','Dulce de Leche Premium'),
('8878','atlhetica-nutrition--best-whey-protein-blitz','Best Whey Protein Blitz','Display 14 un','Duo Crunchy'),
('8812','bold-snacks--bold-bar','Bold Bar','Display 12 un 60g','Bombom Crocante'),
('8808','bold-snacks--bold-bar','Bold Bar','Display 12 un 60g','Cookies e Cream'),
('8804','bold-snacks--bold-bar','Bold Bar','Display 12 un 60g','Trufa de Chocolate'),
('8719','dasenhora--pipoca-artesanal','Pipoca Artesanal','90g','Chocolate & Coco'),
('8482','max-titanium--power-protein-bar','Power Protein Bar','Display 12 un 41g','Frutas Vermelhas'),
('6534','atlhetica-nutrition--best-whey-protein-ball','Best Whey Protein Ball','Display 12 un 50g','Dark Milk Crunchy'),
('6531','atlhetica-nutrition--best-whey-protein-ball','Best Whey Protein Ball','Display 12 un 50g','Cookies & Cream Crunchy'),
('3465','bendu--crispy-wafer','Crispy Wafer','Display 12 un 40g','Pistache'),
('3407','max-titanium--power-protein-bar','Power Protein Bar','Display 12 un 41g','Milk Caramel'),
('3406','max-titanium--power-protein-bar','Power Protein Bar','Display 12 un 41g','Dark Chocolate Truffle'),
('3405','max-titanium--power-protein-bar','Power Protein Bar','Display 12 un 41g','Chocolate com Coco'),
('3404','max-titanium--power-protein-bar','Power Protein Bar','Display 12 un 41g','Cookies'),
('3402','max-titanium--power-protein-bar','Power Protein Bar','Display 12 un 41g','Bombom de Avela com Coco'),
('2072','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Leite Ninho com Creme de Avela'),
('1922','dasenhora--pipoca-artesanal','Pipoca Artesanal','90g','Rapadura e Coco'),
('1921','dasenhora--pipoca-artesanal','Pipoca Artesanal','90g','Cookies e Cream'),
('1917','atlhetica-nutrition--best-whey-bar-12g-protein','Best Whey Bar 12g Protein','Display 12 un 49g','Bianco & Al Latte'),
('1916','atlhetica-nutrition--best-whey-bar-12g-protein','Best Whey Bar 12g Protein','Display 12 un 49g','Cheesecake de Maracuja'),
('1881','atlhetica-nutrition--best-whey-bar-12g-protein','Best Whey Bar 12g Protein','Display 12 un 49g','Leite, Cacau e Avelã'),
('1880','atlhetica-nutrition--best-whey-bar-12g-protein','Best Whey Bar 12g Protein','Display 12 un 49g','Morango Perfeito'),
('1735','atlhetica-nutrition--best-whey-bar-15g-protein','Best Whey Bar 15g Protein','Display 12 un 62g','Crocante de Caramelo'),
('1578','nutrata--protobar-havanna','Protobar Havanna','Display 9 un 70g','Brownie de Chocolate com Dulce de Leche'),
('1573','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Duo Crunch'),
('1552','nutrata--protobar-havanna','Protobar Havanna','Display 9 un 70g','Dulce de Leche'),
('1551','nutrata--whey-grego-bar-havanna','Whey Grego Bar Havanna','Display 12 un 40g','Dulce de Leche'),
('1516','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Cookies and Cream'),
('1472','nutrata--whey-grego-bar','Whey Grego Bar','Display 12 un 40g','Mousse de Maracujá'),
('1439','nutrata--whey-grego-bar','Whey Grego Bar','Display 12 un 40g','Beijinho'),
('1438','nutrata--whey-grego-bar','Whey Grego Bar','Display 12 un 40g','Brigadeiro'),
('1437','nutrata--whey-grego-bar','Whey Grego Bar','Display 12 un 40g','Morango com Chantilly'),
('1379','integralmedica--protein-crisp-bar','Protein Crisp Bar','Display 12 un 45g','Trufa de Avela'),
('1331','atlhetica-nutrition--best-whey-bar-15g-protein','Best Whey Bar 15g Protein','Display 12 un 62g','Chocolate Crocante'),
('1329','atlhetica-nutrition--best-whey-bar-15g-protein','Best Whey Bar 15g Protein','Display 12 un 62g','Cheesecake de Morango'),
('12842','ta-suplementos--xbull','Xbull','Pote 300g','Energetico'),
('12841','ta-suplementos--xbull','Xbull','Pote 300g','Cereja Ice'),
('12795','ta-suplementos--vampire-black','Vampire Black','Pote 140g','Morango com Maracujá'),
('12794','ta-suplementos--vampire-black','Vampire Black','Pote 140g','Uva com Limão'),
('12793','ta-suplementos--vampire-black','Vampire Black','Pote 140g','Maçã Verde'),
('12792','ta-suplementos--vampire-black','Vampire Black','Pote 140g','Tangerina'),
('12776','fullife-nutrition--tomahawk','Tomahawk','Pote 380g','Red Ice'),
('12772','fullife-nutrition--tomahawk','Tomahawk','Pote 380g','Tangerina'),
('12768','fullife-nutrition--tomahawk-night','Tomahawk Night','Pote 380g','Tangerina'),
('12767','fullife-nutrition--tomahawk-night','Tomahawk Night','Pote 380g','Melancia'),
('12766','fullife-nutrition--tomahawk','Tomahawk','Pote 380g','Energy Ice'),
('12765','fullife-nutrition--tomahawk','Tomahawk','Pote 380g','Green Apple'),
('12764','fullife-nutrition--tomahawk','Tomahawk','Pote 380g','Enigma'),
('12757','ta-suplementos--nun','Nun','Pote 280g','Maracujá'),
('12756','demons-lab--insane-clown','Insane Clown','Pote 210g','Fruit Punch'),
('12755','demons-lab--insane-clown','Insane Clown','Pote 210g','Grape'),
('12750','demons-lab--psichotic-t','Psichotic T','Pote 245g','Fruit Energy'),
('12749','demons-lab--insane-clown','Insane Clown','Pote 350g','Manga'),
('12746','us-nutrition--pre-work','Pre Work','Pote 300g','Guaraná com Açaí e Pimenta'),
('12743','ta-suplementos--nun','Nun','Pote 280g','Tangerina'),
('12742','us-nutrition--pre-work','Pre Work','Pote 150g','Maçã Verde'),
('12732','us-nutrition--pre-work','Pre Work','Pote 300g','Uva'),
('12731','us-nutrition--pre-work','Pre Work','Pote 150g','Blue Ice'),
('12730','us-nutrition--pre-work','Pre Work','Pote 300g','Blue Ice'),
('12727','us-nutrition--pre-work','Pre Work','Pote 300g','Frutas Vermelhas'),
('12557','shark-pro--shark-energy','Shark Energy','Pote 150g','Maracujá'),
('12555','shark-pro--shark-energy','Shark Energy','Pote 150g','Tangerina'),
('12554','shark-pro--shark-energy','Shark Energy','Pote 150g','Uva'),
('12502','max-titanium--horus-7-belo','Horus - 7 Belo','Pote 300g',null),
('12489','max-titanium--horus-elite','Horus Elite','Pote 390g','Pink Lemonade'),
('12433','darkness--evora-vulcan-spicy','Evora Vulcan Spicy','Pote 300g','Melon'),
('12422','demons-lab--insane-clown','Insane Clown','Pote 350g','Mad Bull'),
('12400','shark-pro--shark-energy','Shark Energy','Pote 300g','Açai & Guaraná'),
('12399','shark-pro--shark-energy','Shark Energy','Pote 300g','Limão'),
('12398','shark-pro--shark-energy','Shark Energy','Pote 300g','Maracujá'),
('12397','shark-pro--shark-energy','Shark Energy','Pote 300g','Melancia'),
('12396','shark-pro--shark-energy','Shark Energy','Pote 300g','Tangerina'),
('12395','shark-pro--shark-energy','Shark Energy','Pote 300g','Uva'),
('12394','demons-lab--insane-clown','Insane Clown','Pote 210g','Chocolate'),
('12393','demons-lab--insane-clown','Insane Clown','Pote 210g','Pink Lemonade'),
('12362','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Tangerina'),
('12361','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Maçã Verde'),
('12359','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Uva com Limão'),
('12358','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Limonada Suiça'),
('12357','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Morango com Laranja'),
('12355','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Maracujá com Morango'),
('12341','vitafor--v-fort-ultra','V-fort Ultra','Pote 240g','Uva'),
('12274','ta-suplementos--xbull','Xbull','Pote 300g','Maracujá'),
('12273','ta-suplementos--xbull','Xbull','Pote 300g','Morango com Maracujá'),
('12272','ta-suplementos--xbull','Xbull','Pote 300g','Uva com Limão'),
('12271','ta-suplementos--xbull','Xbull','Pote 300g','Limão Siciliano'),
('12270','ta-suplementos--xbull','Xbull','Pote 300g','Laranja com Morango'),
('12269','ta-suplementos--xbull','Xbull','Pote 300g','Tangerina'),
('12096','demons-lab--ectoplasma-super-power','Ectoplasma Super Power','Pote 480g','Blue Vanilla'),
('12094','demons-lab--insane-ghost','Insane Ghost','Pote 350g','Frutas Vermelhas'),
('12093','demons-lab--psichotic-dragon','Psichotic Dragon','Display 30 un 10g',null),
('12092','demons-lab--crack-pw','Crack PW','Display 30 un 10g','Tutti Fruit'),
('12091','demons-lab--ectoplasma-super-power','Ectoplasma Super Power','Pote 480g','Tutti Fruit'),
('11873','atlhetica-nutrition--beta-hd-0-caffeine-com-stevia','Beta HD 0% Caffeine com Stevia','Pote 240g','Pink Limonade'),
('11834','demons-lab--insane-original','Insane Original','Display 30 un 5g','Fruit Punch'),
('11833','demons-lab--insane-mad','Insane Mad','Pote 350g','Fruit Punch'),
('11832','demons-lab--insane-original','Insane Original','Pote 300g','Grape'),
('11831','demons-lab--insane-original','Insane Original','Pote 300g','Orange'),
('11830','demons-lab--insane-original','Insane Original','Pote 300g','Fruit Punch'),
('11742','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Uva'),
('11741','ta-suplementos--precious-pw-diamond-series','Precious PW Diamond Series','Pote 300g','Morango'),
('11720','max-titanium--shook-linha-rafael-brandao','Shook Linha Rafael Brandão','Pote 300g','Uva'),
('11711','darkness--evora-xt','Evora XT','Pote 300g','Bloody Berry'),
('11710','darkness--evora-xt','Evora XT','Pote 300g','Orange Storm'),
('10948','demons-lab--insane-clown','Insane Clown','Pote 350g','Morango com Kiwi (gummy Candy)'),
('10947','demons-lab--insane-clown','Insane Clown','Pote 350g','Blue Crystal'),
('10946','demons-lab--insane-clown','Insane Clown','Pote 350g','Fruit Punch'),
('10945','demons-lab--insane-clown','Insane Clown','Pote 350g','Blue Vanilla'),
('10944','demons-lab--insane-clown','Insane Clown','Pote 350g','Grape'),
('10943','demons-lab--insane-clown','Insane Clown','Pote 350g','Sour Strips'),
('10469','atlhetica-nutrition--x7','X7','Pote 300g','Ki-suco Uva'),
('10174','rpx-nutrition--vesuvio-pw','Vesuvio PW','Pote 300g','Frutas Vermelhas'),
('9095','ta-suplementos--vampire-black','Vampire Black','Pote 140g','Uva (blood Wine)'),
('9060','ta-suplementos--vampire-black','Vampire Black','Pote 140g','Morango (devils Blood)'),
('9030','new-millen--c4-black-beta-pump-explosion','C4 Black Beta Pump Explosion','Display 22 sachês 10g','Fusion Punch'),
('8888','ta-suplementos--vampire-night','Vampire Night','Pote 140g','Blue Blood (algodao Doce)'),
('8721','ta-suplementos--nun','Nun','Pote 280g','Cotton Candy'),
('8720','ta-suplementos--nun','Nun','Pote 230g','Uva'),
('8585','ta-suplementos--nun','Nun','Pote 230g','Maçã Verde'),
('8583','ta-suplementos--nun','Nun','Pote 280g','Morango'),
('6327','max-titanium--night-train','Night Train','Pote 300g','Citrus'),
('6326','max-titanium--night-train','Night Train','Pote 300g','Frutas Vermelhas'),
('5921','new-millen--c4-beta-pump','C4 Beta Pump','Pote 225g','Frutas Amarelas'),
('3956','bodyaction--nuclear-rush','Nuclear Rush','Pote 100g','Laranja'),
('3955','bodyaction--nuclear-rush','Nuclear Rush','Pote 100g','Abacaxi'),
('2549','darkness--evora-pw','Evora PW','Pote 300g','Frutas Amarelas'),
('2419','adaptogen--panic-packet','Panic Packet','Display 20 sachês 10g','Maçã Verde'),
('2418','adaptogen--panic-packet','Panic Packet','Display 20 sachês 10g','Limonada'),
('2383','new-millen--c4-black-beta-pump-explosion','C4 Black Beta Pump Explosion','Display 22 sachês 10g','Bloody Mary'),
('2379','new-millen--c4-black-beta-pump-explosion','C4 Black Beta Pump Explosion','Display 22 sachês 10g','Crazy Mango'),
('2147','bodyaction--nuclear-rush-gel','Nuclear Rush Gel','Display 10 sachês 25g','Frutas Vermelhas'),
('2141','bodyaction--nuclear-rush','Nuclear Rush','Pote 100g','Morango'),
('2140','bodyaction--nuclear-rush','Nuclear Rush','Pote 100g','Limão'),
('2084','darkness--evora-pw','Evora PW','Pote 300g','Uva'),
('2075','max-titanium--horus','Horus','Pote 300g','Limao Yuzu'),
('1646','atlhetica-nutrition--x7','X7','Pote 300g','Pink Lemonade'),
('1645','atlhetica-nutrition--x7','X7','Pote 300g','Frutas Vermelhas (mix Berries)'),
('1644','atlhetica-nutrition--x7','X7','Pote 300g','Citrus Orange & Lemon'),
('1643','atlhetica-nutrition--x7','X7','Pote 300g','Blue Ice'),
('1596','new-millen--c4-beta-pump','C4 Beta Pump','Pote 225g','Tangerina'),
('1591','atlhetica-nutrition--beta-hd','Beta HD','Pote 240g','Uva com Morango'),
('1574','vitafor--v-fort-ultra','V-fort Ultra','Pote 240g','Limão'),
('1508','darkness--evora-pw','Evora PW','Pote 300g','Maçã Verde'),
('1507','darkness--evora-pw','Evora PW','Pote 300g','Limão'),
('1506','darkness--evora-pw','Evora PW','Pote 300g','Frutas Vermelhas'),
('1498','bodyaction--nuclear-rush','Nuclear Rush','Pote 100g','Uva'),
('1487','max-titanium--horus','Horus','Pote 150g','Blue Ice'),
('1377','vitafor--v-fort','V-fort','Pote 240g','Frutas Vermelhas'),
('12780','fullife-nutrition--multi-daily-life','Multi Daily Life','60 caps',null),
('12763','vitaminlife--cloreto-de-magnesio-250mcg','Cloreto de Magnesio 250mcg','60 caps',null),
('12753','demons-lab--demon-t','Demon T','60 caps',null),
('12715','canibal-inc--gods-sweet-dreams-magnesio-inositol','Gods Sweet Dreams Magnesio Inositol','Pote 220g','Quentão'),
('12478','canibal-inc--gods-sweet-dreams-magnesio-inositol','Gods Sweet Dreams Magnesio Inositol','Pote 220g','Maçã com Canela'),
('12472','trustfuel--fizzup-fluipower-16-comp-efervescentes','Fizzup Fluipower 16 Comp Efervescentes','16 caps','Laranja'),
('12471','trustfuel--fizzup-vitamin-c-16-comp-efervescentes','Fizzup Vitamin C 16 Comp Efervescentes','16 caps','Acerola'),
('12470','trustfuel--fizzup-vitamin-c-16-comp-efervescentes','Fizzup Vitamin C 16 Comp Efervescentes','16 caps','Laranja'),
('12469','trustfuel--fizzup-vitamin-c-16-comp-efervescentes','Fizzup Vitamin C 16 Comp Efervescentes','16 caps','Limão'),
('12458','trustfuel--fizzup-cdz-tripla-acao-16-comp-efervescentes','Fizzup Cdz Tripla Acao 16 Comp Efervescentes','16 caps','Laranja'),
('12444','vitaminlife--triple-magnesium','Triple Magnesium','60 caps',null),
('12372','uniao-vegetal--coenzima-q10-1000mg','Coenzima Q10 1000mg','60 caps',null),
('12368','uniao-vegetal--magnesio-l-treonina-450mg','Magnesio L-treonina 450mg','90 caps',null),
('12351','vitaminlife--chromium-picolinate-250mcg','Chromium Picolinate 250mcg','90 caps',null),
('12350','vitaminlife--condrolife-40mg','Condrolife 40mg','30 caps',null),
('12349','vitaminlife--devita-k2','Devita + K2','60 caps',null),
('12348','vitaminlife--nac-600mg','NAC 600mg','60 caps',null),
('12321','vitafor--imunomult-multivitaminico-1000mg','Imunomult Multivitaminico 1000mg','60 caps',null),
('12280','uniao-vegetal--oleo-de-semente-de-abobora-1340mg','Oleo de Semente de Abobora - 1340mg','60 caps',null),
('12264','vitaminlife--nac-acetilcisteina-propolis-30-caps-vitaminlife','NAC Acetilcisteina + Propolis 30 Caps Vitaminlife','30 caps',null),
('12262','muwiz--vitamina-k2-500mg','Vitamina K2 500mg','60 caps',null),
('12256','uniao-vegetal--magnesio-inositol','Magnesio + Inositol','300g','Blueberry'),
('12254','uniao-vegetal--magnesio-inositol','Magnesio + Inositol','300g','Melancia'),
('12243','bodyaction--magnesio-inositol','Magnesio & Inositol','Pote 210g','Abacaxi com Hortelã'),
('12242','bodyaction--magnesio-inositol','Magnesio & Inositol','Pote 210g','Frutas Vermelhas'),
('11859','uniao-vegetal--vitamina-b12-250mg','Vitamina B12 250mg','60 caps',null),
('11858','uniao-vegetal--magnesio-inositol','Magnesio + Inositol','300g','Maracujá'),
('11739','vitaminlife--b-complex','B Complex','90 caps',null),
('11737','vitaminlife--diarium-multivitamins','Diarium Multivitamins','120 caps',null),
('11734','vitaminlife--vitamina-b12-9-94mcg','Vitamina B12 9.94mcg','60 caps',null),
('11733','vitaminlife--vitamina-d-2000ui','Vitamina D 2000ui','60 caps',null),
('10520','muwiz--calcio-d-500mg','Calcio D 500mg','60 caps',null),
('10514','muwiz--curcumina-em-gotas-tipo-ii-vitamina-d','Curcumina em Gotas + Tipo Ii + Vitamina D','30ml',null),
('10500','muwiz--calcio-mdk-1200mg','Calcio Mdk 1200mg','60 caps',null),
('10499','muwiz--mw-cart-700mg','Mw - Cart 700mg','90 caps',null),
('10494','muwiz--quitosana-spirulina-psyllium-b1-e-cromo-600mg','Quitosana, Spirulina, Psyllium, B1 e Cromo 600mg','120 caps',null),
('10492','muwiz--vitamina-d-k2-em-gotas','Vitamina D + K2 em Gotas','30ml',null),
('10490','muwiz--vitamina-do-complexo-b-500mg','Vitamina do Complexo B 500mg','60 caps',null),
('10488','muwiz--mw-vision-plus-500mg','Mw Vision Plus 500mg','30 caps',null),
('10359','atlhetica-nutrition--go-cramp-block','Go! Cramp Block','60 caps',null),
('6341','cleanlab--curcumin','Curcumin','60 caps',null),
('6166','atlhetica-nutrition--multivitaminico-e-minerais-elements-of-life-a-z','Multivitaminico e Minerais Elements of Life A-z','60 caps',null),
('5811','atlhetica-nutrition--chromium-picolinate-250mcg','Chromium Picolinate 250mcg','60 caps',null),
('5795','atlhetica-nutrition--go-repor-salt','Go! Repor Salt','30 caps',null),
('3344','vitafor--vita-d3-k2','Vita D3 + K2','20ml','Menta'),
('3224','vitafor--vitamina-d3-em-gotas-2-000ui','Vitamina D3 em Gotas 2.000ui','10ml',null),
('1762','ta-suplementos--vitamina-c-zinco','Vitamina C + Zinco','60 caps',null),
('12754','demons-lab--creature','Creature','Pote 300g',null),
('12740','us-nutrition--creatina-100-pure','Creatina 100% Pure','Pote 150g',null),
('12739','us-nutrition--creatina-100-pure','Creatina 100% Pure','Pote 300g',null),
('12553','shark-pro--energy-creatina-plus','Energy Creatina Plus','Pote 300g',null),
('12501','max-titanium--creatina-7-belo','Creatina - 7 Belo','Pote 300g',null),
('12487','canibal-inc--creatina-monohydratada-100-pura','Creatina Monohydratada 100% Pura','Refil 500g',null),
('12456','trustfuel--powerfuel-creatine','Powerfuel Creatine','300g',null),
('12446','trustfuel--powerfuel-creatine','Powerfuel Creatine','100g',null),
('12421','atlhetica-nutrition--creatina-100-pure-createst30-display-20un-saches','Creatina 100% Pure CREATEST30 - Display 20un Sachês','5g',null),
('12420','atlhetica-nutrition--creatina-100-pure-createst30','Creatina 100% Pure CREATEST30','Pote 300g',null),
('12419','atlhetica-nutrition--creatina-100-pure-createst30','Creatina 100% Pure CREATEST30','Refil 500g',null),
('12330','vitafor--creatina','Creatina','Pote 300g',null),
('12224','max-titanium--creatina-creapure','Creatina Creapure','Pote 250g',null),
('11829','probiotica--creatina','Creatina','Display 30 Sticks 5g',null),
('9071','atlhetica-nutrition--creatina','Creatina','120 caps',null),
('6662','vitafor--creatina','Creatina','Pote 100g',null),
('6661','vitafor--creatina-creafort-creapure','Creatina Creafort Creapure','Display 30 sachês 3g',null),
('6328','ta-suplementos--creatina-atp','Creatina ATP','Pote 200g',null),
('5812','atlhetica-nutrition--creatina-100-pure','Creatina 100% Pure','Pote 300g',null),
('5099','shark-pro--creatina','Creatina','Pote 300g','Natural'),
('4079','vitafor--creatina-creafort-creapure','Creatina Creafort Creapure','Pote 300g',null),
('3338','probiotica--creatina','Creatina','Pote 300g',null),
('2362','ta-suplementos--creatina-100-pura','Creatina 100% Pura','Pote 300g',null),
('1575','nutrata--creatina','Creatina','Pote 300g',null),
('1351','max-titanium--creatina','Creatina','Pote 300g',null),
('1350','integralmedica--creatina','Creatina','Pote 300g',null),
('1348','integralmedica--creatina','Creatina','Pote 150g',null),
('12719','bendu--creme-zero','Creme Zero','Pote 150g','Avela Dark Crunchy'),
('12718','bendu--creme-zero','Creme Zero','Pote 150g','Avela com Cacau'),
('12717','bendu--creme-zero','Creme Zero','Pote 150g','Bombom Branco'),
('12196','nutrata--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Leite Trufado'),
('11948','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 400g','Avelã'),
('11946','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 400g','Buenissimo'),
('11943','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 400g','Leite em Pó'),
('11880','nutrata--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Morango'),
('11879','nutrata--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Paçoca'),
('11878','nutrata--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Cookies and Cream'),
('11877','nutrata--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Brownie'),
('11876','nutrata--pasta-de-amendoim-havanna','Pasta de Amendoim Havanna','Pote 600g','Dulce de Leche Crunchy'),
('11875','nutrata--pasta-de-amendoim-havanna','Pasta de Amendoim Havanna','Pote 600g','Dulce de Leche Cream'),
('11857','mrs-taste--creme-spread-coq10-com-whey','Creme Spread COQ10 com Whey','Pote 160g','Doce de Leite Argentino'),
('11856','mrs-taste--creme-spread-mrs-tella-coq10-com-whey','Creme Spread Mrs Tella COQ10 com Whey','Pote 160g','Creme de Avelã'),
('11854','mrs-taste--creme-spread-dubai-com-whey','Creme Spread Dubai com Whey','Pote 160g','Chocolate'),
('11849','mrs-taste--creme-spread-speculoos-com-whey','Creme Spread Speculoos com Whey','Pote 160g',null),
('11617','bendu--creme-zero','Creme Zero','Pote 300g','Pistache'),
('11616','bendu--creme-zero','Creme Zero','Pote 300g','Avelã Bombom Branco'),
('11615','bendu--creme-zero','Creme Zero','Pote 300g','Avela com Cacau'),
('11614','bendu--creme-zero','Creme Zero','Pote 300g','Avela Dark Crunchy'),
('10196','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Banoffee'),
('9253','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Beijinho'),
('6400','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Bombom Italiano'),
('1723','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Avelã'),
('1722','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Cookies e Cream'),
('1721','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Buenissimo'),
('1720','dr-peanut--pasta-de-amendoim','Pasta de Amendoim','Pote 600g','Leite em Pó'),
('12411','shark-pro--carb-shark-up-gel-display-10-saches','Carb Shark Up Gel - Display 10 Sachês','30g','Açaí Guaraná Banana'),
('12406','shark-pro--shark-up-hidro-pro-gel-display-10-saches','Shark Up Hidro PRO Gel - Display 10 Sachês','20g','Limão'),
('12404','shark-pro--shark-up-free-gel-display-10-saches','Shark Up Free Gel - Display 10 Sachês','30g','Tutti Frutti'),
('12403','shark-pro--shark-up-free-gel-display-10-saches','Shark Up Free Gel - Display 10 Sachês','30g','Morango com Maracujá'),
('12402','shark-pro--shark-up-free-gel-display-10-saches','Shark Up Free Gel - Display 10 Sachês','30g','Cola'),
('12401','shark-pro--shark-up-free-gel-display-10-saches','Shark Up Free Gel - Display 10 Sachês','30g','Chocolate'),
('12311','z2-foods--saltz-500-z2','Saltz 500 Z2','Display 10 un 15g','Frutas Vermelhas'),
('12310','z2-foods--saltz-500-z2','Saltz 500 Z2','Display 10 un 15g','Água de Coco'),
('12308','z2-foods--bebida-energetica-em-po','Bebida Energetica em Pó','Display 10 un 45g','Tangerina Gelada'),
('12307','z2-foods--saltz-500-z2','Saltz 500 Z2','Display 10 un 7g','Limão'),
('12306','z2-foods--gel-energetico-z2','Gel Energetico Z2+','Display 10 un 25g','Limão'),
('12305','z2-foods--gel-energetico-z2','Gel Energetico Z2+','Display 10 un 25g','Expresso Duplo'),
('12303','z2-foods--gel-energetico-z2','Gel Energetico Z2','Display 10 un 25g','Limonada Rosa'),
('12302','z2-foods--gel-energetico-z2','Gel Energetico Z2','Display 10 un 25g','Pitaya'),
('12301','z2-foods--gel-energetico-z2','Gel Energetico Z2','Display 10 un 25g','Tangerina'),
('12300','z2-foods--gel-energetico-z2','Gel Energetico Z2','Display 10 un 25g','Frutas Tropicais'),
('12267','probiotica--carb-up-gel-super-formula-display-10-saches','Carb Up Gel Super Formula - Display 10 Sachês','30g','Chocolate'),
('12239','probiotica--carb-up-gel-super-formula-display-10-saches','Carb Up Gel Super Formula - Display 10 Sachês','30g','Caldo de Cana com Limão'),
('11814','probiotica--carb-up-gel-black-display-10-saches','Carb Up Gel Black - Display 10 Sachês','30g','Guaraná com Açaí'),
('11812','probiotica--carb-up-gel-black-display-10-saches','Carb Up Gel Black - Display 10 Sachês','30g','Laranja'),
('11811','probiotica--carb-up-gel-black-display-10-saches','Carb Up Gel Black - Display 10 Sachês','30g','Morango'),
('11810','probiotica--carb-up-gel-black-display-10-saches','Carb Up Gel Black - Display 10 Sachês','30g','Caldo de Cana com Limão'),
('5810','atlhetica-nutrition--go-recovery-gel','Go! Recovery Gel','Display 10 sachês 30g','Morango'),
('5798','atlhetica-nutrition--go-isotonic-drink','Go! Isotonic Drink','Saco 900g','Tangerina'),
('5796','atlhetica-nutrition--go-isotonic-drink','Go! Isotonic Drink','Saco 900g','Lima-limao'),
('2390','atlhetica-nutrition--go-energy-now-gel','Go! Energy Now Gel','Display 10 sachês 30g','Morango com Limao'),
('1711','atlhetica-nutrition--go-energy-now-gel','Go! Energy Now Gel','Display 10 sachês 30g','Laranja com Acerola'),
('12812','fullife-nutrition--thermo-cutter-slim','Thermo Cutter Slim','210g','Red Ice'),
('12782','fullife-nutrition--thermo-cutter-slim','Thermo Cutter Slim','Pote 210g','Frutas Tropicais'),
('12778','fullife-nutrition--cafeina-fullflame-200mg','Cafeina Fullflame 200mg','120 caps',null),
('12777','fullife-nutrition--thermo-cutter-slim','Thermo Cutter Slim','Pote 210g','Abacaxi com Hortelã'),
('12771','fullife-nutrition--thermo-cutter-slim','Thermo Cutter Slim','Pote 210g','Maçã'),
('12770','fullife-nutrition--thermo-cutter-slim','Thermo Cutter Slim','Pote 210g','Melancia'),
('12769','fullife-nutrition--thermo-cutter-slim','Thermo Cutter Slim','Pote 210g','Tangerina'),
('12752','demons-lab--psicho-killer','Psicho Killer','60 caps',null),
('12526','vitafor--curcuma-plus-500mg','Curcuma Plus 500mg','30 caps',null),
('12523','vitafor--termo-plus-display-30-saches','Termo Plus Display 30 Saches','40g','Frutas Vermelhas'),
('12522','vitafor--termo-plus','Termo Plus','240g','Frutas Vermelhas Vitafor'),
('12520','vitafor--v-coffee','V-coffee','Pote 220g',null),
('12268','bodyaction--thermo-abdomen','Thermo Abdomen','60 caps',null),
('12109','max-titanium--2hot','2hot','Pote 200g','Tangerina'),
('12107','max-titanium--2hot','2hot','Pote 200g','Limão'),
('9811','under-labz--dimethylex','Dimethylex','60 caps',null),
('9778','atlhetica-nutrition--go-energy-now','Go! Energy Now','60 caps',null),
('9028','new-millen--c4-caffeine-free-com-colina','C4 Caffeine Free com Colina','Pote 220g','Laranja'),
('9027','new-millen--c4-caffeine-free-com-colina','C4 Caffeine Free com Colina','Pote 220g','Limão'),
('9026','new-millen--c4-caffeine-free-com-colina','C4 Caffeine Free com Colina','Pote 220g','Melancia'),
('8880','atlhetica-nutrition--hardcore-yellow','Hardcore Yellow','90 caps',null),
('6167','atlhetica-nutrition--caffeinex-200','Caffeinex 200','60 caps',null),
('4081','vitafor--curcuma-plus-500mg','Curcuma Plus 500mg','60 caps',null),
('2129','bodyaction--night-abdomen','Night Abdomen','60 caps',null),
('1613','atlhetica-nutrition--lipo-burn-hd','Lipo Burn HD','60 caps',null),
('1576','atlhetica-nutrition--lipo-burn-hd-black','Lipo Burn HD Black','Pote 200g','Frutas Vermelhas'),
('12722','awe--sticks-awe-zero-display','Sticks Awe Zero - Display','50g','Limonada Italiana'),
('12721','awe--sticks-awe-zero-display','Sticks Awe Zero - Display','50g','Limão & Blueberry'),
('12720','awe--sticks-awe-zero-display','Sticks Awe Zero - Display','50g','Coco & Morango'),
('12563','red-bull--red-bull-energy-drink','Red Bull Energy Drink','Lata 355ml','Zero'),
('12265','red-bull--red-bull-energy-drink','Red Bull Energy Drink','Lata 250ml','Tradicional'),
('12090','awe--bebida-awe-zero','Bebida Awe Zero','Lata 355ml','Pitaya & Lichia'),
('12089','awe--bebida-awe-zero','Bebida Awe Zero','Lata 355ml','Morango & Kiwi'),
('12088','awe--bebida-awe-zero','Bebida Awe Zero','Lata 355ml','Limão & Gengibre'),
('12087','awe--bebida-awe-zero','Bebida Awe Zero','Lata 355ml','Citrus'),
('11703','vila--agua-mineral','Agua Mineral','500ml','Com Gas'),
('11023','shark-pro--v9-drink','V9 Drink','Lata 269ml','Limão'),
('10957','shark-pro--v9-drink','V9 Drink','Lata 269ml','Energetico'),
('10956','shark-pro--v9-drink','V9 Drink','Lata 269ml','Laranja'),
('10471','monster--monster-energy','Monster Energy','Lata 473ml','Zero'),
('10468','atlhetica-nutrition--x7-smart-the-drink','X7 Smart the Drink','473ml','Ki-suco Uva'),
('10441','new-millen--agent-orange-energy-drink','Agent Orange Energy Drink','Lata 269ml','Tangerina com Morango'),
('10440','new-millen--agent-orange-energy-drink','Agent Orange Energy Drink','Lata 269ml','Limao com Hortela'),
('10147','monster--monster-energy','Monster Energy','Lata 473ml','Original'),
('9245','h2o--h2o-limoneto','H2O Limoneto','500ml',null),
('9145','atlhetica-nutrition--x7-smart-the-drink','X7 Smart the Drink','473ml','Acai Berry'),
('8877','atlhetica-nutrition--x7-smart-the-drink','X7 Smart the Drink','473ml','Espumante'),
('8876','atlhetica-nutrition--x7-smart-the-drink','X7 Smart the Drink','473ml','Caipirinha'),
('8875','atlhetica-nutrition--x7-smart-the-drink','X7 Smart the Drink','473ml','Refresh Citrus'),
('6061','indaia--agua-mineral','Agua Mineral','500ml','Sem Gas'),
('1467','max-titanium--max-energy-lata-framboesa','Max Energy - Lata Framboesa',null,null),
('12632','shark-pro--creajuice','Creajuice','Pote 300g','Laranja com Acerola'),
('12551','shark-pro--energy-creatina-flavour','Energy Creatina Flavour','Pote 300g','Uva'),
('12516','probiotica--nitrato','Nitrato','Pote 220g','Beterraba com Laranja'),
('12455','trustfuel--powerfuel-glutamine','Powerfuel Glutamine','300g',null),
('12335','vitafor--glutamina-glutamax','Glutamina Glutamax','Display 30 sachês 5g',null),
('12253','uniao-vegetal--nac-n-acetil-l-cisteina','NAC N-acetil L-cisteina','60 caps',null),
('11740','vitaminlife--arginina-boro','Arginina + Boro','60 caps',null),
('11700','uniao-vegetal--morotim','Morotim','450ml','Laranja com Frutas Vermelhas'),
('11699','uniao-vegetal--morotim','Morotim','450ml','Maçã Verde'),
('11698','uniao-vegetal--morotim','Morotim','450ml','Morango'),
('11690','uniao-vegetal--morotim','Morotim','450ml','Uva'),
('11675','ta-suplementos--glutamina-diamond','Glutamina Diamond','Pote 300g',null),
('10175','ta-suplementos--arginina-premium-aminoboost','Arginina Premium Aminoboost','120 caps',null),
('10151','nutrata--glutamina','Glutamina','Pote 300g',null),
('8551','vitafor--l-carnitina','L-carnitina','120 caps',null),
('8547','vitafor--glutamina-glutamax','Glutamina Glutamax','Pouch 600g',null),
('7279','atlhetica-nutrition--l-carnitina-2000-chromium','L-carnitina 2000 + Chromium','480ml','Uva'),
('3219','vitafor--glutamina-glutamax','Glutamina Glutamax','Pote 300g',null),
('2361','ta-suplementos--beta-alanina','Beta Alanina','Pote 200g',null),
('2360','ta-suplementos--arginina','Arginina','Pote 100g',null),
('1664','atlhetica-nutrition--l-carnitine-1400','L-carnitine 1400','480ml','Limão'),
('1631','atlhetica-nutrition--l-carnitine-1400','L-carnitine 1400','480ml','Abacaxi'),
('1608','atlhetica-nutrition--beta-alanine-100-pure','Beta Alanine 100% Pure','Pote 200g',null),
('12127','mrs-taste--calda-para-sobremesa-zero','Calda para Sobremesa - Zero','335g','Pumpkin Spice'),
('11838','mrs-taste--calda-para-sobremesa-zero','Calda para Sobremesa - Zero','335g','Cookies and Cream'),
('9336','mrs-taste--molho-mrs-chicken-zero','Molho Mrs Chicken - Zero','320g',null),
('2358','mrs-taste--ketchup-zero','Ketchup Zero','350g','Original'),
('1837','mrs-taste-green--molho-wing-buffalo-zero','Molho Wing Buffalo Zero','320g',null),
('1836','mrs-taste-green--molho-ranch-zero','Molho Ranch - Zero','320g',null),
('1833','mrs-taste--barbecue-zero','Barbecue Zero','350g','Original'),
('1630','mrs-taste--molho-barbecue-zero','Molho Barbecue - Zero','350g','Picante'),
('1628','mrs-taste--mostarda-zero','Mostarda Zero','350g','Original'),
('1565','mrs-taste--calda-para-sobremesa-zero','Calda para Sobremesa - Zero','335g','Doce de Leite'),
('1563','mrs-taste--calda-para-sobremesa-zero','Calda para Sobremesa - Zero','335g','Chocolate'),
('1562','mrs-taste--calda-para-sobremesa-zero','Calda para Sobremesa - Zero','335g','Chocolate com Avela'),
('1561','mrs-taste--calda-para-sobremesa-zero','Calda para Sobremesa - Zero','335g','Morango'),
('1546','mrs-taste-green--molho-para-salada','Molho para Salada','300ml','Ervas Finas'),
('1544','mrs-taste-green--top-taste','Top Taste','320g','Tomate e Goiaba'),
('1542','mrs-taste-green--molho-para-salada','Molho para Salada','300ml','Cebola & Alho'),
('1541','mrs-taste--maionese-zero','Maionese - Zero','335g','Alho'),
('1540','mrs-taste--american-burguer','American Burguer','340g',null),
('1536','mrs-taste--ketchup-zero','Ketchup Zero','350g','Picante'),
('1535','mrs-taste--maionese-zero','Maionese - Zero','335g','Tradicional'),
('12775','fullife-nutrition--full-mass','Full Mass','Pouch 3kg','Chocolate Belga'),
('12774','fullife-nutrition--full-mass','Full Mass','Pouch 3kg','Morango'),
('12773','fullife-nutrition--full-mass','Full Mass','Pouch 3kg','Baunilha'),
('3423','max-titanium--super-gainers','Super Gainers','Saco 3kg','Morango'),
('3422','max-titanium--super-gainers','Super Gainers','Saco 3kg','Chocolate'),
('3421','max-titanium--super-gainers','Super Gainers','Saco 3kg','Baunilha'),
('2487','max-titanium--mass-titanium-17500-zero-lactose-saco','Mass Titanium 17500 Zero Lactose - Saco','2.4kg','Chocolate'),
('2391','max-titanium--mass-titanium-17500-zero-lactose-saco','Mass Titanium 17500 Zero Lactose - Saco','2.4kg','Morango'),
('2337','max-titanium--mass-titanium-17500','Mass Titanium 17500','Saco 3kg','Leite Condensado'),
('2144','bodyaction--hard-mass-18000','Hard Mass 18000','Saco 3kg','Morango'),
('2081','integralmedica--creamass','Creamass','Refil 3kg','Cookies'),
('1607','atlhetica-nutrition--100-hiper-mass-saco','100% Hiper Mass - Saco','2.5kg','Morango'),
('1606','atlhetica-nutrition--100-hiper-mass-saco','100% Hiper Mass - Saco','2.5kg','Chocolate'),
('1365','integralmedica--creamass','Creamass','Refil 3kg','Morango'),
('1364','integralmedica--creamass','Creamass','Refil 3kg','Chocolate'),
('1363','integralmedica--creamass','Creamass','Refil 3kg','Baunilha'),
('12855','shark-pro--shark-isotonic-display-10-saches','Shark Isotonic - Display 10 Sachês','34g','Morango com Maracujá'),
('12854','shark-pro--shark-isotonic-display-10-saches','Shark Isotonic - Display 10 Sachês','34g','Açai com Guaraná'),
('12853','shark-pro--shark-isotonic-display-10-saches','Shark Isotonic - Display 10 Sachês','34g','Limão'),
('12515','probiotica--gel-25pro-boost-display-10-saches','Gel 25pro Boost - Display 10 Sachês','25g','Caramelo Salgado'),
('12514','probiotica--gel-25pro-boost-display-10-saches','Gel 25pro Boost - Display 10 Sachês','25g','Café com Avelã'),
('12513','probiotica--gel-25pro-energy-display-10-saches','Gel 25pro Energy - Display 10 Sachês','25g','Chocolate Maltado'),
('12512','probiotica--gel-25pro-energy-display-10-saches','Gel 25pro Energy - Display 10 Sachês','25g','Cappuccino'),
('12511','probiotica--gel-25pro-hidra-display-10-saches','Gel 25pro Hidra - Display 10 Sachês','25g','Uva Verde'),
('12510','probiotica--gel-25pro-hidra-display-10-saches','Gel 25pro Hidra - Display 10 Sachês','25g','Melancia'),
('12509','probiotica--eletroup-display-10-saches','Eletroup - Display 10 Sachês','8g','Limão'),
('12508','probiotica--eletroup-display-10-saches','Eletroup - Display 10 Sachês','8g','Melancia'),
('12507','probiotica--eletroup-display-10-saches','Eletroup - Display 10 Sachês','8g','Morango com Maracujá'),
('12234','probiotica--mega-malto-dextrin','Mega Malto Dextrin','Caixa 1kg','Morango Silvestre'),
('12233','probiotica--mega-malto-dextrin','Mega Malto Dextrin','Caixa 1kg','Laranja'),
('12232','probiotica--mega-malto-dextrin','Mega Malto Dextrin','Caixa 1kg','Guaraná com Açaí'),
('9148','cleanlab--palatinose-low-g-i','Palatinose Low G.i','Pote 450g',null),
('12779','fullife-nutrition--colageno-hidrolisado','Colageno Hidrolisado','120 caps',null),
('12376','vitafor--colagentek','Colagentek','Pote 300g','Neutro'),
('12352','vitafor--colagentek-protein','Colagentek Protein','Pote 460g','Tangerina'),
('10182','shark-pro--colageno','Colageno','Pote 230g','Cranberry'),
('8559','atlhetica-nutrition--collagen-pure','Collagen Pure','Pote 210g','Frutas Vermelhas'),
('8558','atlhetica-nutrition--collagen-pure','Collagen Pure','Pote 210g','Maracujá'),
('8550','vitafor--colagentek-protein','Colagentek Protein','Pote 460g','Morango'),
('8549','vitafor--colagentek-protein','Colagentek Protein','Pote 460g','Neutro'),
('3223','vitafor--colagentek','Colagentek','Pote 300g','Limão'),
('3220','vitafor--colagentek','Colagentek','Pote 300g','Maçã Verde'),
('3218','vitafor--colagentek','Colagentek','Pote 300g','Tangerina'),
('3217','vitafor--colagentek','Colagentek','Pote 300g','Laranja com Acerola'),
('2138','bodyaction--colageno-acido-hialuronico','Colageno Acido Hialuronico','Pote 200g','Abacaxi com Hortelã'),
('1382','vitafor--colageno-colagentek-tipo-ii','Colageno Colagentek Tipo Ii','60 caps',null),
('12524','vitafor--enzyfor','Enzyfor','Display 10 sachês 3g',null),
('12424','vitafor--end-energy-gel','End Energy Gel','Display 12 sachês 30g','Tangerina'),
('12381','vitafor--end-caffeine-gel','End Caffeine Gel','Display 12 sachês 30g','Chocolate Belga'),
('12354','vitafor--coenzima-q10-100mg','Coenzima Q10 100mg','60 caps',null),
('12337','vitafor--end-caffeine-gel','End Caffeine Gel','Display 12 sachês 30g','Limão'),
('12336','vitafor--end-caffeine-gel','End Caffeine Gel','Display 12 sachês 30g','Mocha'),
('12283','under-labz--coq10-coenzima-200mg','COQ10 Coenzima 200mg','60 caps',null),
('10511','muwiz--lactase-400mg','Lactase 400mg','60 caps',null),
('6351','cleanlab--coenzima-coq10-200mg','Coenzima COQ10 200mg','60 caps',null),
('1340','vitafor--coenzima-q10-200mg','Coenzima Q10 200mg','60 caps',null),
('10154','nutrata--omega-3-1000mg','Omega 3 1000mg','60 caps',null),
('10153','nutrata--omega-3-ultra-tg-1830mg','Omega 3 Ultra Tg 1830mg','60 caps',null),
('10152','nutrata--omega-3-ultra-tg-1830mg','Omega 3 Ultra Tg 1830mg','120 caps',null),
('3222','vitafor--omegafor-plus-1000mg','Omegafor Plus 1000mg','120 caps',null),
('3221','vitafor--omegafor-plus-1000mg','Omegafor Plus 1000mg','60 caps',null),
('1373','vitafor--omega-3-epa-dha-1000mg','Omega 3 EPA - DHA 1000mg','60 caps',null),
('1361','vitafor--omega-3-epa-dha-1000mg','Omega 3 EPA - DHA 1000mg','120 caps',null),
('11738','vitaminlife--curcuma','Curcuma','60 caps',null),
('1495','uniao-vegetal--curcu-curcuma-propolis-e-gengibre','Curcu+ Curcuma, Propolis e Gengibre','30ml',null),
('11743','uniao-vegetal--long-jack-thermo','Long Jack Thermo','450ml','Maçã Verde'),
('11707','uniao-vegetal--long-jack-thermo','Long Jack Thermo','450ml','Tangerina'),
('10522','muwiz--cafe-verde-500mg','Cafe Verde 500mg','60 caps',null),
('10507','muwiz--maca-peruana-100-puro','Maca Peruana 100% Puro','Pote 150g',null)
) as v(cod_forn, grupo, linha, tamanho, sabor)
where p.cod_forn = v.cod_forn;

-- rede de seguranca: SKU novo que entrar sem grupo vira grupo proprio
update produto set grupo = 'sku-' || cod_forn, linha = coalesce(linha, nome)
where grupo is null;

-- ---------------------------------------------------------------------
-- 3. duplicado da NE (mesmo produto, mesmo tamanho, mesmo sabor)
-- ---------------------------------------------------------------------
update produto set ativo = false where cod_forn in ('6357');

-- ---------------------------------------------------------------------
-- 4. catalogo publico (continua sem custo nem margem)
-- ---------------------------------------------------------------------
drop view if exists vitrine;
drop view if exists produto_publico;

create view produto_publico as       -- security definer: roda como dona da view
select id, slug, sku, nome, marca, categoria, familia, grupo, linha, tamanho,
       peso, volume, capsulas, formato, sabor,
       preco_venda_cents, preco_referencia_cents,
       descricao, beneficios, modo_uso, nutricional, foto, disponibilidade
from produto where ativo;

-- ---------------------------------------------------------------------
-- 5. vitrine: uma linha por grupo, ja com a faixa de preco e a contagem
--    de variacoes. E o que as listagens (home, categoria, busca) leem.
--    O representante do grupo e o SKU mais barato.
-- ---------------------------------------------------------------------
create view vitrine as
select distinct on (p.grupo)
       p.grupo,
       p.id, p.slug, p.nome, p.linha, p.marca, p.categoria, p.familia,
       p.sabor, p.tamanho, p.foto, p.disponibilidade,
       p.preco_venda_cents, p.preco_referencia_cents,
       g.preco_max_cents,
       g.qtd_sabores, g.qtd_tamanhos, g.qtd_variacoes
from produto p
join (
  select grupo,
         max(preco_venda_cents)                            as preco_max_cents,
         count(distinct sabor)   filter (where sabor   is not null) as qtd_sabores,
         count(distinct tamanho) filter (where tamanho is not null) as qtd_tamanhos,
         count(*)                                          as qtd_variacoes
  from produto where ativo group by grupo
) g on g.grupo = p.grupo
where p.ativo
order by p.grupo, p.preco_venda_cents asc, p.id;

grant select on produto_publico, vitrine to anon, authenticated;

commit;

-- ---------------------------------------------------------------------
-- conferencia
-- ---------------------------------------------------------------------
select 'produtos ativos'      as o, count(*)::text as r from produto where ativo
union all select 'grupos',              count(*)::text from vitrine
union all select 'grupos com variacao', count(*)::text from vitrine where qtd_variacoes > 1
union all select 'sem grupo',           count(*)::text from produto where grupo is null
union all select 'custo exposto?',
       case when has_column_privilege('anon','produto','custo_ne_cents','select')
            then 'FALHOU' else 'OK' end;
