-- =====================================================================
-- Migracao 02 - busca no cabecalho
-- Rodar no SQL Editor do Supabase DEPOIS da migracao 01.
-- Idempotente: pode rodar de novo.
--
-- Por que uma coluna e nao unaccent() direto: unaccent nao e IMMUTABLE, entao
-- nao entra em coluna gerada nem em indice sem gambiarra. O texto ja vem sem
-- acento e em minusculo daqui, e o site tira o acento do termo digitado antes
-- de consultar. Resultado: "proteina" acha "proteína", sem extensao nenhuma.
-- =====================================================================
begin;

alter table produto add column if not exists busca text;

update produto p set busca = v.busca
from (values
('12860','isofort wpi vitafor isofort wpi display 15un 30g neutro neutro display 15 un 30g proteina isolado'),
('12859','sweet hydro protein canibal inc sweet hydro protein pote 900g limonada suica limonada suica pote 900g proteina whey'),
('12858','sweet hydro protein canibal inc sweet hydro protein pote 900g melancia melancia pote 900g proteina whey'),
('12847','whey protein concentrado dux whey protein concentrado pote 900g caramelo salgado caramelo salgado pote 900g proteina whey'),
('12840','whey powerfuel protein trustfuel whey powerfuel protein 900g chocolate chocolate 900g proteina whey'),
('12839','powerfuel protein uht trustfuel powerfuel protein uht 250ml morango morango 250ml proteina pronta'),
('12838','whey powerfuel protein trustfuel whey powerfuel protein 900g coco coco 900g proteina whey'),
('12837','whey powerfuel protein trustfuel whey powerfuel protein 900g baunilha baunilha 900g proteina whey'),
('12832','recovery uevo recovery saco 1kg morango morango saco 1kg proteina whey'),
('12831','albumina uevo albumina saco 420g cocada cremosa cocada cremosa saco 420g proteina albumina'),
('12830','albumina uevo albumina saco 420g caramelo salgado caramelo salgado saco 420g proteina albumina'),
('12820','whey 100% pure integralmedica whey 100% pure display 10un 20g cookies cookies display 10 un 20g proteina whey'),
('12813','caniblend protein canibal inc caniblend protein refil 900g chocolate branco chocolate branco refil 900g proteina blend'),
('12808','whey beef protein nutrata whey beef protein pote 900g frutas tropicais frutas tropicais pote 900g proteina beef'),
('12807','whey beef protein nutrata whey beef protein pote 900g frutas citricas frutas citricas pote 900g proteina beef'),
('12806','whey beef protein nutrata whey beef protein pote 900g frutas roxas frutas roxas pote 900g proteina beef'),
('12800','caniblend protein canibal inc caniblend protein refil 900g banana banana refil 900g proteina blend'),
('12789','100% whey flavour atlhetica nutrition 100% whey flavour refil 900g chocolate chocolate refil 900g proteina whey'),
('12788','100% whey flavour atlhetica nutrition 100% whey flavour refil 900g leite leite refil 900g proteina whey'),
('12787','carnitech beef protein atlhetica carnitech beef protein pote 840g lemon ice lemon ice pote 840g proteina beef'),
('12786','carnitech beef protein atlhetica carnitech beef protein pote 840g cookies and cream cookies and cream pote 840g proteina beef'),
('12785','carnitech beef protein atlhetica carnitech beef protein pote 840g morango morango pote 840g proteina beef'),
('12784','carnitech beef protein atlhetica carnitech beef protein pote 840g chocolate chocolate pote 840g proteina beef'),
('12783','carnitech beef protein atlhetica carnitech beef protein pote 840g vanilla caramel vanilla caramel pote 840g proteina beef'),
('12741','100% whey us nutrition 100% whey pote 900g cookies cookies pote 900g proteina whey'),
('12738','100% whey us nutrition 100% whey pote 900g chocolate belga chocolate belga pote 900g proteina whey'),
('12737','100% whey us nutrition 100% whey pote 900g morango morango pote 900g proteina whey'),
('12736','100% whey us nutrition 100% whey pote 900g leite ninho leite ninho pote 900g proteina whey'),
('12735','100% whey us nutrition 100% whey pote 900g ovo maltine ovo maltine pote 900g proteina whey'),
('12734','100% whey us nutrition 100% whey pote 900g baunilha baunilha pote 900g proteina whey'),
('12726','power whey us nutrition power whey pote 900g chocolate belga chocolate belga pote 900g proteina whey'),
('12724','power whey us nutrition power whey pote 900g leitinho leitinho pote 900g proteina whey'),
('12698','sweet hydro protein canibal inc sweet hydro protein pote 900g manga com pessego manga com pessego pote 900g proteina whey'),
('12641','albumina uevo albumina saco 420g banoffee banoffee saco 420g proteina albumina'),
('12633','albumina uevo albumina saco 1kg banoffee banoffee saco 1kg proteina albumina'),
('12548','100% pure whey probiotica 100% pure whey pote 900g caramelo salgado caramelo salgado pote 900g proteina whey'),
('12535','whey 100% pure integralmedica whey 100% pure display 10un 20g chocolate chocolate display 10 un 20g proteina whey'),
('12534','whey 100% pure integralmedica whey 100% pure display 10un 20g baunilha baunilha display 10 un 20g proteina whey'),
('12504','whey beef protein display 10 saches shark pro whey beef protein display 10 saches 35g abacaxi com hortela abacaxi com hortela 35g proteina beef'),
('12503','whey protein joypro display 10 saches shark pro whey protein joypro display 10 saches 33g brigadeiro brigadeiro 33g proteina whey'),
('12499','whey protein joypro display 10 saches shark pro whey protein joypro display 10 saches 33g cookies de banana com canela cookies de banana com canela 33g proteina whey'),
('12496','whey beef protein display 10 saches shark pro whey beef protein display 10 saches 35g morango com maracuja morango com maracuja 35g proteina beef'),
('12486','whey beef protein shark pro whey beef protein pote 900g abacaxi com hortela abacaxi com hortela pote 900g proteina beef'),
('12484','whey beef protein shark pro whey beef protein pote 900g melancia com limao melancia com limao pote 900g proteina beef'),
('12479','sweet hydro protein canibal inc sweet hydro protein pote 900g abacaxi com hortela abacaxi com hortela pote 900g proteina whey'),
('12476','whey beef protein display 10 saches shark pro whey beef protein display 10 saches 35g laranja com acerola laranja com acerola 35g proteina beef'),
('12474','whey protein joypro display 10 saches shark pro whey protein joypro display 10 saches 33g iogurte morango com framboesa iogurte morango com framboesa 33g proteina whey'),
('12473','whey protein joypro shark pro whey protein joypro pote 900g leite leite pote 900g proteina whey'),
('12468','goalmy protein 90 gomas trustfuel goalmy protein 90 gomas baunilha baunilha proteina whey'),
('12465','powerfuel protein uht trustfuel powerfuel protein uht 250ml cookiescream cookiescream 250ml proteina pronta'),
('12457','goalmy protein 90 gomas trustfuel goalmy protein 90 gomas chocolate chocolate proteina whey'),
('12454','powerfuel protein trustfuel powerfuel protein 450g baunilha baunilha 450g proteina whey'),
('12453','powerfuel protein trustfuel powerfuel protein 450g chocolate chocolate 450g proteina whey'),
('12452','powerfuel protein trustfuel powerfuel protein 450g coco coco 450g proteina whey'),
('12451','powerfuel protein uht trustfuel powerfuel protein uht 250ml chocolate chocolate 250ml proteina pronta'),
('12450','powerfuel protein uht trustfuel powerfuel protein uht 250ml coco coco 250ml proteina pronta'),
('12415','wheycrea ta suplementos wheycrea pote 900g torta de chocolate torta de chocolate pote 900g proteina whey'),
('12414','wheycrea ta suplementos wheycrea pote 900g torta de morango torta de morango pote 900g proteina whey'),
('12413','wheycrea ta suplementos wheycrea pote 900g chocoleite chocoleite pote 900g proteina whey'),
('12412','wheycrea ta suplementos wheycrea pote 900g cookiesmaltine cookiesmaltine pote 900g proteina whey'),
('12391','gods whey 100% canibal inc gods whey 100% refil 900g chocolate chocolate refil 900g proteina whey'),
('12390','gods whey 100% canibal inc gods whey 100% refil 900g baunilha baunilha refil 900g proteina whey'),
('12389','caniblend protein canibal inc caniblend protein refil 900g morango morango refil 900g proteina blend'),
('12388','caniblend protein canibal inc caniblend protein refil 900g baunilha baunilha refil 900g proteina blend'),
('12387','caniblend protein canibal inc caniblend protein refil 900g leite leite refil 900g proteina blend'),
('12386','caniblend protein canibal inc caniblend protein refil 900g cookies cookies refil 900g proteina blend'),
('12385','caniblend protein canibal inc caniblend protein refil 900g chocolate chocolate refil 900g proteina blend'),
('12383','gods whey 100% canibal inc gods whey 100% refil 900g morango morango refil 900g proteina whey'),
('12380','whey wpc pouch vitafor whey wpc pouch pote 900g baunilha baunilha pote 900g proteina whey'),
('12379','whey wpc pouch vitafor whey wpc pouch pote 900g beijinho beijinho pote 900g proteina whey'),
('12378','whey wpc pouch vitafor whey wpc pouch pote 900g morango morango pote 900g proteina whey'),
('12377','whey wpc pouch vitafor whey wpc pouch pote 900g mousse de maracuja mousse de maracuja pote 900g proteina whey'),
('12375','whey protein concentrado dux whey protein concentrado pote 900g cappuccino cappuccino pote 900g proteina whey'),
('12366','100% whey protein pro nutri 100% whey protein saco 900g leite em po leite em po saco 900g proteina whey'),
('12365','100% whey protein pro nutri 100% whey protein saco 900g leite em po e morango leite em po e morango saco 900g proteina whey'),
('12364','wheycrea ta suplementos wheycrea pote 900g mousse de baunilha mousse de baunilha pote 900g proteina whey'),
('12363','wheycrea ta suplementos wheycrea pote 900g brigadeiro branco brigadeiro branco pote 900g proteina whey'),
('12360','pure whey protein display 12 saches uniao vegetal pure whey protein display 12 saches 30g malte crocante malte crocante 30g proteina whey'),
('12356','isocrisp plant vitafor isocrisp plant pote 60g pote 60g proteina vegana'),
('12345','isocrisp vitafor isocrisp pote 60g neutro neutro pote 60g proteina crisp'),
('12344','isocrisp plant vitafor isocrisp plant pouch 240g pouch 240g proteina vegana'),
('12343','isocrisp whey pote neutro pouch vitafor isocrisp whey pote neutro pouch 240g 240g proteina crisp'),
('12331','isofort ultra imuno vitafor isofort ultra imuno pote 900g cacau cacau pote 900g proteina isolado'),
('12326','isofort wpi vitafor isofort wpi display 15un 30g baunilha baunilha display 15 un 30g proteina isolado'),
('12325','isofort wpi vitafor isofort wpi display 15un 30g chocolate chocolate display 15 un 30g proteina isolado'),
('12324','isofort wpi vitafor isofort wpi display 15un 30g frutas vermelhas frutas vermelhas display 15 un 30g proteina isolado'),
('12323','isofort ultra imuno vitafor isofort ultra imuno pote 900g baunilha baunilha pote 900g proteina isolado'),
('12296','best whey atlhetica nutrition best whey display 15un 40g milkshake morango bobs milkshake morango bobs display 15 un 40g proteina whey'),
('12293','whey zero leite tres sensacoes ta suplementos whey zero leite pote 900g tres sensacoes pote 900g proteina whey'),
('12292','whey zero leite ta suplementos whey zero leite pote 900g sorvete de doce de leite sorvete de doce de leite pote 900g proteina whey'),
('12287','whey zero leite ta suplementos whey zero leite pote 900g coffee caramel coffee caramel pote 900g proteina whey'),
('12279','best whey atlhetica nutrition best whey pote 900g milkshake morango bobs milkshake morango bobs pote 900g proteina whey'),
('12252','carnbull ta suplementos carnbull pote 900g maca verde maca verde pote 900g proteina beef'),
('12231','carnbull ta suplementos carnbull pote 900g uva uva pote 900g proteina beef'),
('12228','whey protein joypro shark pro whey protein joypro refil 900g pacoca pacoca refil 900g proteina whey'),
('12225','whey protein joypro shark pro whey protein joypro refil 900g cookies banana com canela cookies banana com canela refil 900g proteina whey'),
('12221','100% whey double tasty max titanium 100% whey double tasty pote 900g morango morango pote 900g proteina whey'),
('12220','bold whey bold snacks bold whey display 10un 30g doce de leite doce de leite display 10 un 30g proteina whey'),
('12212','carnbull ta suplementos carnbull pote 900g limonada suica limonada suica pote 900g proteina beef'),
('12153','whey protein joypro shark pro whey protein joypro pote 900g brigadeiro brigadeiro pote 900g proteina whey'),
('12152','whey protein joypro shark pro whey protein joypro pote 900g cookies banana com canela cookies banana com canela pote 900g proteina whey'),
('12151','whey protein joypro shark pro whey protein joypro pote 900g iogurte morango com framboesa iogurte morango com framboesa pote 900g proteina whey'),
('12150','whey protein joypro shark pro whey protein joypro pote 900g pacoca pacoca pote 900g proteina whey'),
('12019','isolate protein new millen isolate protein pote 900g abacaxi com hortela abacaxi com hortela pote 900g proteina isolado'),
('12018','isolate protein new millen isolate protein pote 900g orange juice orange juice pote 900g proteina isolado'),
('11951','whey blend 3w saco 1.8kg + 400g gratis ta suplementos whey blend 3w saco 1.8kg + 400g gratis milkshake de baunilha milkshake de baunilha 1.8kg proteina blend'),
('11885','w100 whey display 12 saches nutrata w100 whey display 12 saches 30g morango morango 30g proteina whey'),
('11884','w100 whey display 12 saches nutrata w100 whey display 12 saches 30g creme de baunilha creme de baunilha 30g proteina whey'),
('11883','w100 whey display 12 saches nutrata w100 whey display 12 saches 30g duplo chocolate duplo chocolate 30g proteina whey'),
('11882','w100 whey display 12 saches nutrata w100 whey display 12 saches 30g cookies & cream cookies e cream 30g proteina whey'),
('11881','w100 whey havanna display 12 saches nutrata w100 whey havanna display 12 saches 20g doce de leite doce de leite 20g proteina whey'),
('11861','albumina uevo albumina saco 420g cafe mocaccino cafe mocaccino saco 420g proteina albumina'),
('11860','albumina uevo albumina saco 1kg cafe mocaccino cafe mocaccino saco 1kg proteina albumina'),
('11808','100% pure whey probiotica 100% pure whey pote 900g baunilha baunilha pote 900g proteina whey'),
('11807','100% pure whey probiotica 100% pure whey pote 900g morango morango pote 900g proteina whey'),
('11806','100% pure whey probiotica 100% pure whey pote 900g cookies e cream cookies e cream pote 900g proteina whey'),
('11804','100% pure whey probiotica 100% pure whey pote 900g iogurte com limao iogurte com limao pote 900g proteina whey'),
('11803','100% pure whey probiotica 100% pure whey pote 900g iogurte com morango iogurte com morango pote 900g proteina whey'),
('11799','whey beef protein shark pro whey beef protein pote 900g morango kiwi morango kiwi pote 900g proteina beef'),
('11798','whey beef protein shark pro whey beef protein pote 900g morango com maracuja morango com maracuja pote 900g proteina beef'),
('11797','whey beef protein shark pro whey beef protein pote 900g frutas roxas frutas roxas pote 900g proteina beef'),
('11796','whey beef protein shark pro whey beef protein pote 900g laranja com acerola laranja com acerola pote 900g proteina beef'),
('11795','whey beef protein shark pro whey beef protein pote 900g frutas tropicais frutas tropicais pote 900g proteina beef'),
('11729','bold whey bold snacks bold whey display 10un 30g cookies e cream cookies e cream display 10 un 30g proteina whey'),
('11726','bold whey bold snacks bold whey display 10un 30g mousse de morango mousse de morango display 10 un 30g proteina whey'),
('11696','whey w100 nutrata whey w100 refil 900g cookies cookies refil 900g proteina whey'),
('11695','whey w100 nutrata whey w100 refil 900g creme de coco creme de coco refil 900g proteina whey'),
('11680','best whey atlhetica nutrition best whey display 15 saches 37g pistache & original pistache & original display 15 saches 37g proteina whey'),
('11679','best whey atlhetica nutrition best whey pote 900g pistache & original pistache & original pote 900g proteina whey'),
('10979','pure blend 100% protein lacto free refil atlhetica nutrition pure blend 100% protein lacto free refil 1.814kg baunilha baunilha 1.814kg proteina blend'),
('10978','pure blend 100% protein lacto free refil atlhetica nutrition pure blend 100% protein lacto free refil 1.814kg chocolate chocolate 1.814kg proteina blend'),
('10963','pure blend 100% protein lacto free atlhetica nutrition pure blend 100% protein lacto free refil 907g baunilha baunilha refil 907g proteina blend'),
('10962','pure blend 100% protein lacto free atlhetica nutrition pure blend 100% protein lacto free refil 907g chocolate chocolate refil 907g proteina blend'),
('10961','pure blend 100% protein lacto free atlhetica nutrition pure blend 100% protein lacto free refil 907g creme de avela creme de avela refil 907g proteina blend'),
('10952','carnibol darkness carnibol pote 900g baunilha baunilha pote 900g proteina beef'),
('10487','albumina naturovos albumina saco 420g natural natural saco 420g proteina albumina'),
('10486','albumina uevo albumina saco 1kg chocolate chocolate saco 1kg proteina albumina'),
('10485','albumina uevo albumina saco 1kg morango morango saco 1kg proteina albumina'),
('10484','albumina uevo albumina saco 1kg baunilha baunilha saco 1kg proteina albumina'),
('10483','albumina uevo albumina saco 420g chocolate chocolate saco 420g proteina albumina'),
('10482','albumina uevo albumina saco 420g morango morango saco 420g proteina albumina'),
('10481','albumina uevo albumina saco 420g baunilha baunilha saco 420g proteina albumina'),
('10480','albumina naturovos albumina saco 1kg natural natural saco 1kg proteina albumina'),
('10332','100% whey protein pro nutri 100% whey protein saco 900g milkshake de baunilha milkshake de baunilha saco 900g proteina whey'),
('10330','100% whey protein pro nutri 100% whey protein saco 900g chocolate chocolate saco 900g proteina whey'),
('10145','whey 100% pure integralmedica whey 100% pure refil 900g gelato di latte gelato di latte refil 900g proteina whey'),
('9991','whey zero leite ta suplementos whey zero leite pote 900g sorvete de morango sorvete de morango pote 900g proteina whey'),
('9990','whey zero leite ta suplementos whey zero leite pote 900g sorvete de chocolate sorvete de chocolate pote 900g proteina whey'),
('9877','best whey toddy achocolatado atlhetica nutrition best whey toddy pote 450g achocolatado pote 450g proteina whey'),
('9876','best whey achocolatado toddy atlhetica nutrition best whey display 15 saches 40g achocolatado toddy display 15 saches 40g proteina whey'),
('9875','best whey toddy achocolatado atlhetica nutrition best whey pote 900g toddy achocolatado pote 900g proteina whey'),
('9287','muscle whey 3w proforce muscle whey 3w saco 2kg chocolate chocolate saco 2kg proteina blend'),
('9281','muscle whey 3w proforce muscle whey 3w saco 2kg morango morango saco 2kg proteina blend'),
('8560','best whey atlhetica nutrition best whey display 15 saches 40g brownie chocolate brownie chocolate display 15 saches 40g proteina whey'),
('8557','best whey atlhetica nutrition best whey display 15 saches 40g leite cacau e avela leite cacau e avela display 15 saches 40g proteina whey'),
('8555','best whey atlhetica nutrition best whey display 15 saches 40g double chocolate double chocolate display 15 saches 40g proteina whey'),
('8553','best whey atlhetica nutrition best whey display 15 saches 35g vanilla cream vanilla cream display 15 saches 35g proteina whey'),
('8510','best whey atlhetica nutrition best whey display 15 saches 40g brigadeiro gourmet brigadeiro gourmet display 15 saches 40g proteina whey'),
('8459','best whey atlhetica nutrition best whey display 15 saches 37g chocolate branco chocolate branco display 15 saches 37g proteina whey'),
('7345','100% whey protein shark pro 100% whey protein refil 900g chocolate chocolate refil 900g proteina whey'),
('6690','100% whey prime bodyaction 100% whey prime pote 900g baunilha baunilha pote 900g proteina whey'),
('6689','100% whey prime bodyaction 100% whey prime pote 900g chocolate chocolate pote 900g proteina whey'),
('6688','100% whey prime bodyaction 100% whey prime pote 900g morango morango pote 900g proteina whey'),
('6665','100% pure whey probiotica 100% pure whey refil 900g iogurte com coco iogurte com coco refil 900g proteina whey'),
('6532','best whey atlhetica nutrition best whey pote 900g brigadeiro gourmet brigadeiro gourmet pote 900g proteina whey'),
('6357','100% whey flavour atlhetica nutrition 100% whey flavour refil 900g chocolate chocolate refil 900g proteina whey'),
('6168','best whey atlhetica nutrition best whey display 15 saches 35g dulce de leche premium dulce de leche premium display 15 saches 35g proteina whey'),
('6161','best whey atlhetica nutrition best whey pote 900g dulce de leche premium dulce de leche premium pote 900g proteina whey'),
('6056','100% pure whey probiotica 100% pure whey refil 900g cookies & cream cookies e cream refil 900g proteina whey'),
('5813','100% pure whey probiotica 100% pure whey refil 900g iogurte com morango iogurte com morango refil 900g proteina whey'),
('5807','whey w100 nutrata whey w100 pote 900g creme de coco creme de coco pote 900g proteina whey'),
('5804','whey w100 nutrata whey w100 pote 900g chocolate chocolate pote 900g proteina whey'),
('5044','best vegan atlhetica nutrition best vegan pote 500g cacau cacau pote 500g proteina vegana'),
('3949','isolate definition refil bodyaction isolate definition refil 1.8kg morango morango 1.8kg proteina isolado'),
('3948','isolate definition refil bodyaction isolate definition refil 1.8kg baunilha baunilha 1.8kg proteina isolado'),
('3947','isolate definition refil bodyaction isolate definition refil 1.8kg chocolate chocolate 1.8kg proteina isolado'),
('3912','tasty whey 3w adaptogen tasty whey 3w pote 900g chocomaltine chocomaltine pote 900g proteina blend'),
('3379','pure whey concentrado pure suplementos pure whey concentrado pote 1kg coco coco pote 1kg proteina whey'),
('3341','100% pure whey probiotica 100% pure whey pote 900g chocolate chocolate pote 900g proteina whey'),
('2137','isolate prime whey bodyaction isolate prime whey pote 900g baunilha baunilha pote 900g proteina isolado'),
('2133','isolate prime whey bodyaction isolate prime whey pote 900g chocolate chocolate pote 900g proteina isolado'),
('2125','isolate definition bodyaction isolate definition pote 900g morango morango pote 900g proteina isolado'),
('2123','isolate definition bodyaction isolate definition pote 900g baunilha baunilha pote 900g proteina isolado'),
('2122','3 whey top taste bodyaction 3 whey top taste pote 900g morango morango pote 900g proteina whey'),
('1785','tasty whey 3w adaptogen tasty whey 3w pote 900g condensed milk condensed milk pote 900g proteina blend'),
('1738','whey fort 3w vitafor whey fort 3w pote 900g frutas vermelhas frutas vermelhas pote 900g proteina blend'),
('1736','whey fort 3w vitafor whey fort 3w pote 900g chocolate chocolate pote 900g proteina blend'),
('1732','whey fort 3w vitafor whey fort 3w pote 900g neutro neutro pote 900g proteina blend'),
('1683','tasty whey 3w adaptogen tasty whey 3w pote 900g dulce de leche dulce de leche pote 900g proteina blend'),
('1682','tasty whey 3w adaptogen tasty whey 3w pote 900g chocotella cream chocotella cream pote 900g proteina blend'),
('1681','tasty whey 3w adaptogen tasty whey 3w pote 900g vanilla cream vanilla cream pote 900g proteina blend'),
('1680','tasty whey 3w adaptogen tasty whey 3w pote 900g chocolate suico chocolate suico pote 900g proteina blend'),
('1678','tasty whey 3w adaptogen tasty whey 3w pote 900g strawberry cream strawberry cream pote 900g proteina blend'),
('1667','isofort plant vitafor isofort plant pote 450g cacau cacau pote 450g proteina vegana'),
('1666','best whey iso atlhetica nutrition best whey iso pote 900g brigadeiro brigadeiro pote 900g proteina isolado'),
('1665','best whey iso atlhetica nutrition best whey iso pote 900g baunilha baunilha pote 900g proteina isolado'),
('1634','best whey atlhetica nutrition best whey pote 900g cookies e cream cookies e cream pote 900g proteina whey'),
('1622','best vegan atlhetica nutrition best vegan pote 500g original original pote 500g proteina vegana'),
('1618','best whey atlhetica nutrition best whey pote 900g original original pote 900g proteina whey'),
('1616','best whey atlhetica nutrition best whey pote 900g double chocolate double chocolate pote 900g proteina whey'),
('1615','best whey atlhetica nutrition best whey pote 900g vanilla cream vanilla cream pote 900g proteina whey'),
('1611','best whey atlhetica nutrition best whey pote 900g leite cacau e avela leite cacau e avela pote 900g proteina whey'),
('1566','whey fort 3w vitafor whey fort 3w pote 900g baunilha baunilha pote 900g proteina blend'),
('1553','isofort plant vitafor isofort plant pote 450g banana com canela banana com canela pote 450g proteina vegana'),
('1520','100% whey prime bodyaction 100% whey prime refil 900g chocolate chocolate refil 900g proteina whey'),
('1492','100% whey max titanium 100% whey refil 900g chocolate chocolate refil 900g proteina whey'),
('1490','100% whey max titanium 100% whey refil 900g morango morango refil 900g proteina whey'),
('1489','100% whey max titanium 100% whey refil 900g baunilha baunilha refil 900g proteina whey'),
('1454','100% whey max titanium 100% whey pote 900g cookies & cream cookies e cream pote 900g proteina whey'),
('1446','whey 100% pure integralmedica whey 100% pure refil 900g cookies and cream cookies and cream refil 900g proteina whey'),
('1445','whey 100% pure integralmedica whey 100% pure refil 900g baunilha baunilha refil 900g proteina whey'),
('1444','whey 100% pure integralmedica whey 100% pure refil 900g chocolate chocolate refil 900g proteina whey'),
('1442','whey protein concentrado dux whey protein concentrado pote 900g coco coco pote 900g proteina whey'),
('1425','isolate prime whey bodyaction isolate prime whey pote 900g morango morango pote 900g proteina isolado'),
('1404','whey protein concentrado dux whey protein concentrado pote 900g baunilha baunilha pote 900g proteina whey'),
('1402','isofort plant vitafor isofort plant pote 450g baunilha baunilha pote 450g proteina vegana'),
('1371','top whey 3w + performance max titanium top whey 3w + performance pote 900g morango morango pote 900g proteina blend'),
('1369','top whey 3w + performance max titanium top whey 3w + performance pote 900g chocolate chocolate pote 900g proteina blend'),
('1368','top whey 3w + performance max titanium top whey 3w + performance pote 900g baunilha baunilha pote 900g proteina blend'),
('1345','isofort vitafor isofort pote 900g neutro neutro pote 900g proteina isolado'),
('1344','isofort vitafor isofort pote 900g frutas vermelhas frutas vermelhas pote 900g proteina isolado'),
('1343','isofort vitafor isofort pote 900g chocolate chocolate pote 900g proteina isolado'),
('1342','isofort vitafor isofort pote 900g baunilha baunilha pote 900g proteina isolado'),
('1339','carnibol darkness carnibol pote 900g salt caramelo salt caramelo pote 900g proteina beef'),
('1338','carnibol darkness carnibol pote 900g chocolate chocolate pote 900g proteina beef'),
('1320','3 whey top taste bodyaction 3 whey top taste pote 900g chocolate chocolate pote 900g proteina whey'),
('1319','3 whey top taste bodyaction 3 whey top taste pote 900g baunilha baunilha pote 900g proteina whey'),
('1318','100% pure whey probiotica 100% pure whey refil 900g morango morango refil 900g proteina whey'),
('1317','100% pure whey probiotica 100% pure whey refil 900g chocolate chocolate refil 900g proteina whey'),
('1316','100% pure whey probiotica 100% pure whey refil 900g baunilha baunilha refil 900g proteina whey'),
('1315','100% whey max titanium 100% whey pote 900g morango morango pote 900g proteina whey'),
('1314','100% whey max titanium 100% whey pote 900g chocolate chocolate pote 900g proteina whey'),
('12856','mini crunch shark shark pro mini crunch shark 6un 20g barras sortidas barras sortidas 20g barrinhas e snacks barra'),
('12850','protein bar shark crush shark pro protein bar shark crush display 12un 40g morango com iorgute morango com iorgute display 12 un 40g barrinhas e snacks barra'),
('12849','protein bar shark crush shark pro protein bar shark crush display 12un 40g marshmallow marshmallow display 12 un 40g barrinhas e snacks barra'),
('12848','protein bar shark crush shark pro protein bar shark crush display 12un 40g brigadeiro brigadeiro display 12 un 40g barrinhas e snacks doce'),
('12845','salgadinho proteico salty chips bendu salgadinho proteico salty chips 40g white cheese white cheese 40g barrinhas e snacks salgadinho'),
('12844','salgadinho proteico salty chips bendu salgadinho proteico salty chips 40g sour cream sour cream 40g barrinhas e snacks salgadinho'),
('12843','sweet magic canibal inc sweet magic display 24un 25g peanut butter crocante e coco cream peanut butter crocante e coco cream display 24 un 25g barrinhas e snacks doce'),
('12835','pipoca do johnny johnny pipoca do johnny 75g caramelo e flor de sal caramelo e flor de sal 75g barrinhas e snacks pipoca'),
('12834','pipoca do johnny johnny pipoca do johnny 75g brownie brownie 75g barrinhas e snacks pipoca'),
('12829','pipoca uevo pipoca 75g caramelo e flor de sal caramelo e flor de sal 75g barrinhas e snacks pipoca'),
('12828','pipoca do johnny johnny pipoca do johnny 40g sour cream sour cream 40g barrinhas e snacks pipoca'),
('12818','chips de proteina irreal snacks chips de proteina 40g paprica picante paprica picante 40g barrinhas e snacks salgadinho'),
('12817','chips de proteina irreal snacks chips de proteina 40g cebola caramelizada cebola caramelizada 40g barrinhas e snacks salgadinho'),
('12815','chips de proteina irreal snacks chips de proteina 40g white cheddar white cheddar 40g barrinhas e snacks salgadinho'),
('12810','bold bar bold snacks bold bar display 12un 40g trufa de chocolate trufa de chocolate display 12 un 40g barrinhas e snacks barra'),
('12801','sweet magic canibal inc sweet magic display 24un 20g leitinho leitinho display 24 un 20g barrinhas e snacks doce'),
('12796','sweet magic canibal inc sweet magic display 24un 20g doce de leite doce de leite display 24 un 20g barrinhas e snacks doce'),
('12762','salgadinho proteico supley salgadinho proteico 40g cebola e salsa cebola e salsa 40g barrinhas e snacks salgadinho'),
('12761','salgadinho proteico supley salgadinho proteico 40g pesto e parmesao pesto e parmesao 40g barrinhas e snacks salgadinho'),
('12646','crispy wafer bendu crispy wafer display 12un 40g malte chocolate malte chocolate display 12 un 40g barrinhas e snacks wafer'),
('12564','brigadeiro mel 12 unidades ta suplementos brigadeiro mel 12 unidades barrinhas e snacks doce'),
('12562','salgadinho proteico zig fit nutrata salgadinho proteico zig fit 40g lemon pepper lemon pepper 40g barrinhas e snacks salgadinho'),
('12561','salgadinho proteico zig fit nutrata salgadinho proteico zig fit 40g dois queijos dois queijos 40g barrinhas e snacks salgadinho'),
('12560','salgadinho proteico zig fit nutrata salgadinho proteico zig fit 40g barbecue barbecue 40g barrinhas e snacks salgadinho'),
('12517','salgadinho proteico supley salgadinho proteico 40g cheeseburger cheeseburger 40g barrinhas e snacks salgadinho'),
('12493','power protein crisp bar max titanium power protein crisp bar display 12un 44g banoffee banoffee display 12 un 44g barrinhas e snacks barra'),
('12492','power protein crisp bar max titanium power protein crisp bar display 12un 44g cappuccino cappuccino display 12 un 44g barrinhas e snacks barra'),
('12481','gods wafer canibal inc gods wafer display 6un 51g coco coco display 6 un 51g barrinhas e snacks wafer'),
('12480','gods wafer canibal inc gods wafer display 6un 51g cookies e cream cookies e cream display 6 un 51g barrinhas e snacks wafer'),
('12430','yopro bar nutrata yopro bar display 12un 55g cappuccino cappuccino display 12 un 55g barrinhas e snacks barra'),
('12429','whey grego bar havanna zero nutrata whey grego bar havanna zero display 12un 40g doce de leite doce de leite display 12 un 40g barrinhas e snacks barra'),
('12369','sublime bendu sublime display 10un 40g baunilha baunilha display 10 un 40g barrinhas e snacks barra'),
('12329','snack assado fitzei vitafor snack assado fitzei saco 45g churrasco churrasco saco 45g barrinhas e snacks barra'),
('12320','barra tamara + colageno verisol nature foodtech barra tamara + colageno verisol display 12un 35g chocolate meio amargo chocolate meio amargo display 12 un 35g barrinhas e snacks barra'),
('12319','barra tamara + colageno verisol nature foodtech barra tamara + colageno verisol display 12un 35g morango morango display 12 un 35g barrinhas e snacks barra'),
('12317','barra tamara + creatina creapure nature foodtech barra tamara + creatina creapure display 12un 35g chocolate meio amargo chocolate meio amargo display 12 un 35g barrinhas e snacks barra'),
('12316','barra tamara + creatina creapure nature foodtech barra tamara + creatina creapure display 12un 35g morango morango display 12 un 35g barrinhas e snacks barra'),
('12314','barra tamara + colageno verisol nature foodtech barra tamara + colageno verisol display 12un 35g cookies and cream cookies and cream display 12 un 35g barrinhas e snacks barra'),
('12312','protobar charge caramelo amendoim e cobertura de chocolate nutrata protobar charge display 12un 45g caramelo amendoim e cobertura de chocolate display 12 un 45g barrinhas e snacks barra'),
('12299','barz mini barra energetica z2 z2 foods barz mini barra energetica z2 display 10un 30g chocolate com amendoim chocolate com amendoim display 10 un 30g barrinhas e snacks barra'),
('12298','barz mini barra energetica z2 z2 foods barz mini barra energetica z2 display 10un 30g bagas limao siciliano bagas limao siciliano display 10 un 30g barrinhas e snacks barra'),
('12229','barra nutrata bacio di latte nutrata barra nutrata bacio di latte display 12un 45g caramelo salgado caramelo salgado display 12 un 45g barrinhas e snacks barra'),
('11853','taste cookie bar mrs taste taste cookie bar display 12un 50g salted pao de alho salted pao de alho display 12 un 50g barrinhas e snacks barra'),
('11850','taste cookie bar mrs taste taste cookie bar display 12un 50g morango morango display 12 un 50g barrinhas e snacks barra'),
('11848','taste cookie bar mrs taste taste cookie bar display 12un 50g doce de leite argentino doce de leite argentino display 12 un 50g barrinhas e snacks barra'),
('11846','taste cookie bar mrs taste taste cookie bar display 12un 50g cookies and cream cookies and cream display 12 un 50g barrinhas e snacks barra'),
('11843','taste cookie bar mrs taste taste cookie bar display 12un 50g salted pepperoni salted pepperoni display 12 un 50g barrinhas e snacks barra'),
('11841','taste cookie bar mrs taste taste cookie bar display 12un 50g salted marguerita salted marguerita display 12 un 50g barrinhas e snacks barra'),
('11840','taste cookie bar mrs taste taste cookie bar display 12un 50g speculoos caramelo com especiarias speculoos caramelo com especiarias display 12 un 50g barrinhas e snacks barra'),
('11822','soft bar bendu soft bar display 12un 45g dark chocolate dark chocolate display 12 un 45g barrinhas e snacks barra'),
('11819','whey bar creamy probiotica whey bar creamy display 12un 38g chocolate chocolate display 12 un 38g barrinhas e snacks barra'),
('11732','bold bar bold snacks bold bar display 12un 40g bombom crocante bombom crocante display 12 un 40g barrinhas e snacks barra'),
('11731','bold bar bold snacks bold bar display 12un 40g cookies e cream cookies e cream display 12 un 40g barrinhas e snacks barra'),
('11730','bold bar bold snacks bold bar display 12un 40g pistache pistache display 12 un 40g barrinhas e snacks barra'),
('11709','protein crisp bar integralmedica protein crisp bar display 12un 45g ovomaltine ovomaltine display 12 un 45g barrinhas e snacks barra'),
('11697','barra nutrata bacio di latte nutrata barra nutrata bacio di latte display 12un 40g pistache pistache display 12 un 40g barrinhas e snacks barra'),
('11694','yopro bar nutrata yopro bar display 12un 55g morango com chocolate branco morango com chocolate branco display 12 un 55g barrinhas e snacks barra'),
('11678','best whey bar 15g protein atlhetica nutrition best whey bar 15g protein display 12un 49g pistache & original pistache & original display 12 un 49g barrinhas e snacks barra'),
('11677','crispy wafer bendu crispy wafer display 12un 40g dark chocolate dark chocolate display 12 un 40g barrinhas e snacks wafer'),
('11673','bold crunch bold snacks bold crunch display 12un 60g brigadeiro brigadeiro display 12 un 60g barrinhas e snacks doce'),
('11672','bold crunch bold snacks bold crunch display 12un 60g cookies & cream cookies e cream display 12 un 60g barrinhas e snacks barra'),
('11656','pacoca whey zero barrinhas e snacks pacoca whey zero 20g natural bendu natural bendu 20g barrinhas e snacks pacoca'),
('11609','pacoca zero bendu pacoca zero display 24un 20g natural natural display 24 un 20g barrinhas e snacks pacoca'),
('11608','pacoca whey bendu pacoca whey display 24un 20g cookies cookies display 24 un 20g barrinhas e snacks pacoca'),
('11607','pacoca whey bendu pacoca whey display 24un 20g leite em po leite em po display 24 un 20g barrinhas e snacks pacoca'),
('11606','pacoca whey bendu pacoca whey display 24un 20g doce de leite doce de leite display 24 un 20g barrinhas e snacks pacoca'),
('11605','pacoca whey bendu pacoca whey display 24un 20g cookie de chocolate cookie de chocolate display 24 un 20g barrinhas e snacks pacoca'),
('11601','sublime bendu sublime display 10un 40g avela avela display 10 un 40g barrinhas e snacks barra'),
('11600','sublime bendu sublime display 10un 40g doce de leite doce de leite display 10 un 40g barrinhas e snacks barra'),
('11599','sublime bendu sublime display 10un 40g cookies cookies display 10 un 40g barrinhas e snacks barra'),
('11598','sublime bendu sublime display 10un 40g pistache pistache display 10 un 40g barrinhas e snacks barra'),
('11596','soft bar bendu soft bar display 12un 45g cookies cookies display 12 un 45g barrinhas e snacks barra'),
('11594','soft bar bendu soft bar display 12un 45g leite em po leite em po display 12 un 45g barrinhas e snacks barra'),
('10972','doctor bar dr. peanut doctor bar display 8un 62g cookies & cream cookies e cream display 8 un 62g barrinhas e snacks barra'),
('10971','doctor bar dr. peanut doctor bar display 8un 62g doce de leite doce de leite display 8 un 62g barrinhas e snacks barra'),
('10472','yopro bar nutrata yopro bar display 12un 55g chocolate chocolate display 12 un 55g barrinhas e snacks barra'),
('10417','power protein crisp bar max titanium power protein crisp bar display 12un 44g cookies cookies display 12 un 44g barrinhas e snacks barra'),
('10415','power protein crisp bar max titanium power protein crisp bar display 12un 44g frutas vermelhas frutas vermelhas display 12 un 44g barrinhas e snacks barra'),
('10157','whey grego bar havanna nutrata whey grego bar havanna display 12un 40g brownie de chocolate com dulce de leche brownie de chocolate com dulce de leche display 12 un 40g barrinhas e snacks barra'),
('10156','whey grego bar havanna nutrata whey grego bar havanna display 12un 40g banoffee com dulce de leche banoffee com dulce de leche display 12 un 40g barrinhas e snacks barra'),
('10134','best whey protein ball atlhetica nutrition best whey protein ball display 12un 50g dulce de leche premium dulce de leche premium display 12 un 50g barrinhas e snacks doce'),
('9996','bold bar bold snacks bold bar display 12un 60g pistache pistache display 12 un 60g barrinhas e snacks barra'),
('9262','barra nutrata nutrata barra nutrata display 12un 45g caramel protein caramel protein display 12 un 45g barrinhas e snacks barra'),
('9252','barra nutrata nutrata barra nutrata display 12un 45g dark caramel protein dark caramel protein display 12 un 45g barrinhas e snacks barra'),
('9223','salgadinho proteico shark pro salgadinho proteico 50g salsa e cebola salsa e cebola 50g barrinhas e snacks salgadinho'),
('9222','salgadinho proteico shark pro salgadinho proteico 50g churrasco churrasco 50g barrinhas e snacks salgadinho'),
('9221','salgadinho proteico shark pro salgadinho proteico 50g requeijao requeijao 50g barrinhas e snacks salgadinho'),
('9073','protein crisp bar integralmedica protein crisp bar display 12un 45g creme de coco creme de coco display 12 un 45g barrinhas e snacks barra'),
('8884','protein crisp bar integralmedica protein crisp bar display 12un 45g brownie de chocolate brownie de chocolate display 12 un 45g barrinhas e snacks barra'),
('8879','best whey bar 15g protein atlhetica nutrition best whey bar 15g protein display 12un 62g dulce de leche premium dulce de leche premium display 12 un 62g barrinhas e snacks barra'),
('8878','best whey protein blitz atlhetica nutrition best whey protein blitz display 14un 7 5g duo crunchy duo crunchy display 14 un barrinhas e snacks doce'),
('8812','bold bar bold snacks bold bar display 12un 60g bombom crocante bombom crocante display 12 un 60g barrinhas e snacks barra'),
('8808','bold bar bold snacks bold bar display 12un 60g cookies e cream cookies e cream display 12 un 60g barrinhas e snacks barra'),
('8804','bold bar bold snacks bold bar display 12un 60g trufa de chocolate trufa de chocolate display 12 un 60g barrinhas e snacks barra'),
('8719','pipoca artesanal dasenhora pipoca artesanal 90g chocolate & coco chocolate & coco 90g barrinhas e snacks pipoca'),
('8482','power protein bar max titanium power protein bar display 12un 41g frutas vermelhas frutas vermelhas display 12 un 41g barrinhas e snacks barra'),
('6534','best whey protein ball atlhetica nutrition best whey protein ball display 12un 50g dark milk crunchy dark milk crunchy display 12 un 50g barrinhas e snacks doce'),
('6531','best whey protein ball atlhetica nutrition best whey protein ball display 12un 50g cookies & cream crunchy cookies & cream crunchy display 12 un 50g barrinhas e snacks doce'),
('3465','crispy wafer bendu crispy wafer display 12un 40g pistache pistache display 12 un 40g barrinhas e snacks wafer'),
('3407','power protein bar max titanium power protein bar display 12un 41g milk caramel milk caramel display 12 un 41g barrinhas e snacks barra'),
('3406','power protein bar max titanium power protein bar display 12un 41g dark chocolate truffle dark chocolate truffle display 12 un 41g barrinhas e snacks barra'),
('3405','power protein bar max titanium power protein bar display 12un 41g chocolate com coco chocolate com coco display 12 un 41g barrinhas e snacks barra'),
('3404','power protein bar max titanium power protein bar display 12un 41g cookies cookies display 12 un 41g barrinhas e snacks barra'),
('3402','power protein bar max titanium power protein bar display 12un 41g bombom de avela com coco bombom de avela com coco display 12 un 41g barrinhas e snacks barra'),
('2072','protein crisp bar integralmedica protein crisp bar display 12un 45g leite ninho com creme de avela leite ninho com creme de avela display 12 un 45g barrinhas e snacks barra'),
('1922','pipoca artesanal dasenhora pipoca artesanal 90g rapadura e coco rapadura e coco 90g barrinhas e snacks pipoca'),
('1921','pipoca artesanal dasenhora pipoca artesanal 90g cookies & cream cookies e cream 90g barrinhas e snacks pipoca'),
('1917','best whey bar 12g protein atlhetica nutrition best whey bar 12g protein display 12un 49g bianco & al latte bianco & al latte display 12 un 49g barrinhas e snacks barra'),
('1916','best whey bar 12g protein atlhetica nutrition best whey bar 12g protein display 12un 49g cheesecake de maracuja cheesecake de maracuja display 12 un 49g barrinhas e snacks barra'),
('1881','best whey bar 12g protein atlhetica nutrition best whey bar 12g protein display 12un 49g leite cacau & avela leite cacau e avela display 12 un 49g barrinhas e snacks barra'),
('1880','best whey bar 12g protein atlhetica nutrition best whey bar 12g protein display 12un 49g morango perfeito morango perfeito display 12 un 49g barrinhas e snacks barra'),
('1735','best whey bar 15g protein atlhetica nutrition best whey bar 15g protein display 12un 62g crocante de caramelo crocante de caramelo display 12 un 62g barrinhas e snacks barra'),
('1578','protobar havanna nutrata protobar havanna display 9un 70g brownie de chocolate com dulce de leche brownie de chocolate com dulce de leche display 9 un 70g barrinhas e snacks barra'),
('1573','protein crisp bar integralmedica protein crisp bar display 12un 45g duo crunch duo crunch display 12 un 45g barrinhas e snacks barra'),
('1552','protobar havanna nutrata protobar havanna display 9un 70g dulce de leche dulce de leche display 9 un 70g barrinhas e snacks barra'),
('1551','whey grego bar havanna nutrata whey grego bar havanna display 12un 40g dulce de leche dulce de leche display 12 un 40g barrinhas e snacks barra'),
('1516','protein crisp bar integralmedica protein crisp bar display 12un 45g cookies and cream cookies and cream display 12 un 45g barrinhas e snacks barra'),
('1472','whey grego bar nutrata whey grego bar display 12un 40g mousse de maracuja mousse de maracuja display 12 un 40g barrinhas e snacks barra'),
('1439','whey grego bar nutrata whey grego bar display 12un 40g beijinho beijinho display 12 un 40g barrinhas e snacks barra'),
('1438','whey grego bar nutrata whey grego bar display 12un 40g brigadeiro brigadeiro display 12 un 40g barrinhas e snacks doce'),
('1437','whey grego bar nutrata whey grego bar display 12un 40g morango com chantilly morango com chantilly display 12 un 40g barrinhas e snacks barra'),
('1379','protein crisp bar integralmedica protein crisp bar display 12un 45g trufa de avela trufa de avela display 12 un 45g barrinhas e snacks barra'),
('1331','best whey bar 15g protein atlhetica nutrition best whey bar 15g protein display 12un 62g chocolate crocante chocolate crocante display 12 un 62g barrinhas e snacks barra'),
('1329','best whey bar 15g protein atlhetica nutrition best whey bar 15g protein display 12un 62g cheesecake de morango cheesecake de morango display 12 un 62g barrinhas e snacks barra'),
('12842','xbull ta suplementos xbull pote 300g energetico energetico pote 300g pre treino pre'),
('12841','xbull ta suplementos xbull pote 300g cereja ice cereja ice pote 300g pre treino pre'),
('12795','vampire black ta suplementos vampire black pote 140g morango com maracuja morango com maracuja pote 140g pre treino pre'),
('12794','vampire black ta suplementos vampire black pote 140g uva com limao uva com limao pote 140g pre treino pre'),
('12793','vampire black ta suplementos vampire black pote 140g maca verde maca verde pote 140g pre treino pre'),
('12792','vampire black ta suplementos vampire black pote 140g tangerina tangerina pote 140g pre treino pre'),
('12776','tomahawk fullife nutrition tomahawk pote 380g red ice red ice pote 380g pre treino pre'),
('12772','tomahawk fullife nutrition tomahawk pote 380g tangerina tangerina pote 380g pre treino pre'),
('12768','tomahawk night fullife nutrition tomahawk night pote 380g tangerina tangerina pote 380g pre treino pre sem cafeina'),
('12767','tomahawk night fullife nutrition tomahawk night pote 380g melancia melancia pote 380g pre treino pre sem cafeina'),
('12766','tomahawk fullife nutrition tomahawk pote 380g energy ice energy ice pote 380g pre treino pre'),
('12765','tomahawk fullife nutrition tomahawk pote 380g green apple green apple pote 380g pre treino pre'),
('12764','tomahawk fullife nutrition tomahawk pote 380g enigma enigma pote 380g pre treino pre'),
('12757','nun ta suplementos nun pote 280g maracuja maracuja pote 280g pre treino pre'),
('12756','insane clown demons lab insane clown pote 210g fruit punch fruit punch pote 210g pre treino pre'),
('12755','insane clown demons lab insane clown pote 210g grape grape pote 210g pre treino pre'),
('12750','psichotic t demons lab psichotic t pote 245g fruit energy fruit energy pote 245g pre treino pre'),
('12749','insane clown demons lab insane clown pote 350g manga manga pote 350g pre treino pre'),
('12746','pre work us nutrition pre work pote 300g guarana com acai e pimenta guarana com acai e pimenta pote 300g pre treino pre'),
('12743','nun ta suplementos nun pote 280g tangerina tangerina pote 280g pre treino pre'),
('12742','pre work us nutrition pre work pote 150g maca verde maca verde pote 150g pre treino pre'),
('12732','pre work us nutrition pre work pote 300g uva uva pote 300g pre treino pre'),
('12731','pre work us nutrition pre work pote 150g blue ice blue ice pote 150g pre treino pre'),
('12730','pre work us nutrition pre work pote 300g blue ice blue ice pote 300g pre treino pre'),
('12727','pre work us nutrition pre work pote 300g frutas vermelhas frutas vermelhas pote 300g pre treino pre'),
('12557','shark energy shark pro shark energy pote 150g maracuja maracuja pote 150g pre treino pre'),
('12555','shark energy shark pro shark energy pote 150g tangerina tangerina pote 150g pre treino pre'),
('12554','shark energy shark pro shark energy pote 150g uva uva pote 150g pre treino pre'),
('12502','horus 7 belo max titanium horus pote 300g 7 belo pote 300g pre treino pre'),
('12489','horus elite max titanium horus elite pote 390g pink lemonade pink lemonade pote 390g pre treino pre'),
('12433','evora vulcan spicy darkness evora vulcan spicy pote 300g melon melon pote 300g pre treino pre'),
('12422','insane clown demons lab insane clown pote 350g mad bull mad bull pote 350g pre treino pre'),
('12400','shark energy shark pro shark energy pote 300g acai & guarana acai & guarana pote 300g pre treino pre'),
('12399','shark energy shark pro shark energy pote 300g limao limao pote 300g pre treino pre'),
('12398','shark energy shark pro shark energy pote 300g maracuja maracuja pote 300g pre treino pre'),
('12397','shark energy shark pro shark energy pote 300g melancia melancia pote 300g pre treino pre'),
('12396','shark energy shark pro shark energy pote 300g tangerina tangerina pote 300g pre treino pre'),
('12395','shark energy shark pro shark energy pote 300g uva uva pote 300g pre treino pre'),
('12394','insane clown demons lab insane clown pote 210g chocolate chocolate pote 210g pre treino pre'),
('12393','insane clown demons lab insane clown pote 210g pink lemonade pink lemonade pote 210g pre treino pre'),
('12362','precious pw diamond series ta suplementos precious pw diamond series pote 300g tangerina tangerina pote 300g pre treino pre'),
('12361','precious pw diamond series ta suplementos precious pw diamond series pote 300g maca verde maca verde pote 300g pre treino pre'),
('12359','precious pw diamond series ta suplementos precious pw diamond series pote 300g uva com limao uva com limao pote 300g pre treino pre'),
('12358','precious pw diamond series ta suplementos precious pw diamond series pote 300g limonada suica limonada suica pote 300g pre treino pre'),
('12357','precious pw diamond series ta suplementos precious pw diamond series pote 300g morango com laranja morango com laranja pote 300g pre treino pre'),
('12355','precious pw diamond series ta suplementos precious pw diamond series pote 300g maracuja com morango maracuja com morango pote 300g pre treino pre'),
('12341','v fort ultra vitafor v fort ultra pote 240g uva uva pote 240g pre treino pre'),
('12274','xbull ta suplementos xbull pote 300g maracuja maracuja pote 300g pre treino pre'),
('12273','xbull ta suplementos xbull pote 300g morango com maracuja morango com maracuja pote 300g pre treino pre'),
('12272','xbull ta suplementos xbull pote 300g uva com limao uva com limao pote 300g pre treino pre'),
('12271','xbull ta suplementos xbull pote 300g limao siciliano limao siciliano pote 300g pre treino pre'),
('12270','xbull ta suplementos xbull pote 300g laranja com morango laranja com morango pote 300g pre treino pre'),
('12269','xbull ta suplementos xbull pote 300g tangerina tangerina pote 300g pre treino pre'),
('12096','ectoplasma super power demons lab ectoplasma super power pote 480g blue vanilla blue vanilla pote 480g pre treino pre'),
('12094','insane ghost demons lab insane ghost pote 350g frutas vermelhas frutas vermelhas pote 350g pre treino pre'),
('12093','psichotic dragon demons lab psichotic dragon display 30un 10g display 30 un 10g pre treino pre sache'),
('12092','crack pw demons lab crack pw display 30un 10g tutti fruit tutti fruit display 30 un 10g pre treino pre sache'),
('12091','ectoplasma super power demons lab ectoplasma super power pote 480g tutti fruit tutti fruit pote 480g pre treino pre'),
('11873','beta hd 0% caffeine com stevia atlhetica nutrition beta hd 0% caffeine com stevia pote 240g pink limonade pink limonade pote 240g pre treino pre sem cafeina'),
('11834','insane original demons lab insane original display 30un 5g fruit punch fruit punch display 30 un 5g pre treino pre sache'),
('11833','insane mad demons lab insane mad pote 350g fruit punch fruit punch pote 350g pre treino pre'),
('11832','insane original demons lab insane original pote 300g grape grape pote 300g pre treino pre'),
('11831','insane original demons lab insane original pote 300g orange orange pote 300g pre treino pre'),
('11830','insane original demons lab insane original pote 300g fruit punch fruit punch pote 300g pre treino pre'),
('11742','precious pw diamond series ta suplementos precious pw diamond series pote 300g uva uva pote 300g pre treino pre'),
('11741','precious pw diamond series ta suplementos precious pw diamond series pote 300g morango morango pote 300g pre treino pre'),
('11720','shook linha rafael brandao max titanium shook linha rafael brandao pote 300g uva uva pote 300g pre treino pre'),
('11711','evora xt darkness evora xt pote 300g bloody berry bloody berry pote 300g pre treino pre'),
('11710','evora xt darkness evora xt pote 300g orange storm orange storm pote 300g pre treino pre'),
('10948','insane clown demons lab insane clown pote 350g morango com kiwi gummy candy morango com kiwi gummy candy pote 350g pre treino pre'),
('10947','insane clown demons lab insane clown pote 350g blue crystal blue crystal pote 350g pre treino pre'),
('10946','insane clown demons lab insane clown pote 350g fruit punch fruit punch pote 350g pre treino pre'),
('10945','insane clown demons lab insane clown pote 350g blue vanilla blue vanilla pote 350g pre treino pre'),
('10944','insane clown demons lab insane clown pote 350g grape grape pote 350g pre treino pre'),
('10943','insane clown demons lab insane clown pote 350g sour strips sour strips pote 350g pre treino pre'),
('10469','x7 atlhetica nutrition x7 pote 300g ki suco uva ki suco uva pote 300g pre treino pre'),
('10174','vesuvio pw rpx nutrition vesuvio pw pote 300g frutas vermelhas frutas vermelhas pote 300g pre treino pre'),
('9095','vampire black ta suplementos vampire black pote 140g uva blood wine uva blood wine pote 140g pre treino pre'),
('9060','vampire black ta suplementos vampire black pote 140g morango devils blood morango devils blood pote 140g pre treino pre'),
('9030','c4 black beta pump explosion new millen c4 black beta pump explosion display 22 saches 10g fusion punch fusion punch display 22 saches 10g pre treino pre sache'),
('8888','vampire night ta suplementos vampire night pote 140g blue blood algodao doce blue blood algodao doce pote 140g pre treino pre sem cafeina'),
('8721','nun ta suplementos nun pote 280g cotton candy cotton candy pote 280g pre treino pre'),
('8720','nun ta suplementos nun pote 230g uva uva pote 230g pre treino pre'),
('8585','nun ta suplementos nun pote 230g maca verde maca verde pote 230g pre treino pre'),
('8583','nun ta suplementos nun pote 280g morango morango pote 280g pre treino pre'),
('6327','night train max titanium night train pote 300g citrus citrus pote 300g pre treino pre sem cafeina'),
('6326','night train max titanium night train pote 300g frutas vermelhas frutas vermelhas pote 300g pre treino pre sem cafeina'),
('5921','c4 beta pump new millen c4 beta pump pote 225g frutas amarelas frutas amarelas pote 225g pre treino pre'),
('3956','nuclear rush bodyaction nuclear rush pote 100g laranja laranja pote 100g pre treino pre'),
('3955','nuclear rush bodyaction nuclear rush pote 100g abacaxi abacaxi pote 100g pre treino pre'),
('2549','evora pw darkness evora pw pote 300g frutas amarelas frutas amarelas pote 300g pre treino pre'),
('2419','panic packet adaptogen panic packet display 20 saches 10g maca verde maca verde display 20 saches 10g pre treino pre sache'),
('2418','panic packet adaptogen panic packet display 20 saches 10g limonada limonada display 20 saches 10g pre treino pre sache'),
('2383','c4 black beta pump explosion new millen c4 black beta pump explosion display 22 saches 10g bloody mary bloody mary display 22 saches 10g pre treino pre sache'),
('2379','c4 black beta pump explosion new millen c4 black beta pump explosion display 22 saches 10g crazy mango crazy mango display 22 saches 10g pre treino pre sache'),
('2147','nuclear rush gel bodyaction nuclear rush gel display 10 saches 25g frutas vermelhas frutas vermelhas display 10 saches 25g pre treino pre sache'),
('2141','nuclear rush bodyaction nuclear rush pote 100g morango morango pote 100g pre treino pre'),
('2140','nuclear rush bodyaction nuclear rush pote 100g limao limao pote 100g pre treino pre'),
('2084','evora pw darkness evora pw pote 300g uva uva pote 300g pre treino pre'),
('2075','horus max titanium horus pote 300g limao yuzu limao yuzu pote 300g pre treino pre'),
('1646','x7 atlhetica nutrition x7 pote 300g pink lemonade pink lemonade pote 300g pre treino pre'),
('1645','x7 atlhetica nutrition x7 pote 300g frutas vermelhas mix berries frutas vermelhas mix berries pote 300g pre treino pre'),
('1644','x7 atlhetica nutrition x7 pote 300g citrus orange & lemon citrus orange & lemon pote 300g pre treino pre'),
('1643','x7 atlhetica nutrition x7 pote 300g blue ice blue ice pote 300g pre treino pre'),
('1596','c4 beta pump new millen c4 beta pump pote 225g tangerina tangerina pote 225g pre treino pre'),
('1591','beta hd atlhetica nutrition beta hd pote 240g uva com morango uva com morango pote 240g pre treino pre'),
('1574','v fort ultra vitafor v fort ultra pote 240g limao limao pote 240g pre treino pre'),
('1508','evora pw darkness evora pw pote 300g maca verde maca verde pote 300g pre treino pre'),
('1507','evora pw darkness evora pw pote 300g limao limao pote 300g pre treino pre'),
('1506','evora pw darkness evora pw pote 300g frutas vermelhas frutas vermelhas pote 300g pre treino pre'),
('1498','nuclear rush bodyaction nuclear rush pote 100g uva uva pote 100g pre treino pre'),
('1487','horus max titanium horus pote 150g blue ice blue ice pote 150g pre treino pre'),
('1377','v fort vitafor v fort pote 240g frutas vermelhas frutas vermelhas pote 240g pre treino pre'),
('12780','multi daily life fullife nutrition multi daily life 42g 60 caps 60 caps vitamina mineral multi'),
('12763','cloreto de magnesio 250mcg vitaminlife cloreto de magnesio 250mcg 60 caps 60 caps vitamina mineral magnesio'),
('12753','demon t demons lab demon t 60 caps 60 caps vitamina mineral vitamina'),
('12715','gods sweet dreams magnesio inositol canibal inc gods sweet dreams magnesio inositol pote 220g quentao quentao pote 220g vitamina mineral magnesio'),
('12478','gods sweet dreams magnesio inositol canibal inc gods sweet dreams magnesio inositol pote 220g maca com canela maca com canela pote 220g vitamina mineral magnesio'),
('12472','fizzup fluipower 16 comp efervescentes trustfuel fizzup fluipower 16 comp efervescentes laranja laranja 16 caps vitamina mineral vitamina'),
('12471','fizzup vitamin c 16 comp efervescentes trustfuel fizzup vitamin c 16 comp efervescentes acerola acerola 16 caps vitamina mineral vitamina'),
('12470','fizzup vitamin c 16 comp efervescentes trustfuel fizzup vitamin c 16 comp efervescentes laranja laranja 16 caps vitamina mineral vitamina'),
('12469','fizzup vitamin c 16 comp efervescentes trustfuel fizzup vitamin c 16 comp efervescentes limao limao 16 caps vitamina mineral vitamina'),
('12458','fizzup cdz tripla acao 16 comp efervescentes trustfuel fizzup cdz tripla acao 16 comp efervescentes laranja laranja 16 caps vitamina mineral vitamina'),
('12444','triple magnesium vitaminlife triple magnesium 60 caps 60 caps vitamina mineral vitamina'),
('12372','coenzima q10 1000mg uniao vegetal coenzima q10 1000mg 60 caps 60 caps vitamina mineral vitamina'),
('12368','magnesio l treonina 450mg uniao vegetal magnesio l treonina 450mg 90 caps 90 caps vitamina mineral magnesio'),
('12351','chromium picolinate 250mcg vitaminlife chromium picolinate 250mcg 90 caps 90 caps vitamina mineral vitamina'),
('12350','condrolife 40mg vitaminlife condrolife 40mg 30 caps 30 caps vitamina mineral vitamina'),
('12349','devita + k2 vitaminlife devita + k2 60 caps 60 caps vitamina mineral vitd'),
('12348','nac 600mg vitaminlife nac 600mg 60 caps 60 caps vitamina mineral vitamina'),
('12321','imunomult multivitaminico 1000mg vitafor imunomult multivitaminico 1000mg 60 caps 60 caps vitamina mineral multi'),
('12280','oleo de semente de abobora 1340mg uniao vegetal oleo de semente de abobora 1340mg 60 caps 60 caps vitamina mineral vitamina'),
('12264','nac acetilcisteina + propolis 30 caps vitaminlife vitaminlife nac acetilcisteina + propolis 30 caps vitaminlife 30 caps vitamina mineral vitamina'),
('12262','vitamina k2 500mg muwiz vitamina k2 500mg 60 caps 60 caps vitamina mineral vitamina'),
('12256','magnesio + inositol uniao vegetal magnesio + inositol 300g blueberry blueberry 300g vitamina mineral magnesio'),
('12254','magnesio + inositol uniao vegetal magnesio + inositol 300g melancia melancia 300g vitamina mineral magnesio'),
('12243','magnesio & inositol bodyaction magnesio & inositol pote 210g abacaxi com hortela abacaxi com hortela pote 210g vitamina mineral magnesio'),
('12242','magnesio & inositol bodyaction magnesio & inositol pote 210g frutas vermelhas frutas vermelhas pote 210g vitamina mineral magnesio'),
('11859','vitamina b12 250mg uniao vegetal vitamina b12 250mg 60 caps 60 caps vitamina mineral vitb'),
('11858','magnesio + inositol uniao vegetal magnesio + inositol 300g maracuja maracuja 300g vitamina mineral magnesio'),
('11739','b complex vitaminlife b complex 90 caps 90 caps vitamina mineral vitb'),
('11737','diarium multivitamins vitaminlife diarium multivitamins 120 caps 120 caps vitamina mineral multi'),
('11734','vitamina b12 9.94mcg vitaminlife vitamina b12 9.94mcg 60 caps 60 caps vitamina mineral vitb'),
('11733','vitamina d 2000ui vitaminlife vitamina d 2000ui 60 softgels 60 caps vitamina mineral vitd'),
('10520','calcio d 500mg muwiz calcio d 500mg 60 caps 60 caps vitamina mineral calcio'),
('10514','curcumina em gotas + tipo ii + vitamina d muwiz curcumina em gotas + tipo ii + vitamina d 30ml 30ml vitamina mineral vitd'),
('10500','calcio mdk 1200mg muwiz calcio mdk 1200mg 60 caps 60 caps vitamina mineral calcio'),
('10499','mw cart 700mg muwiz mw cart 700mg 90 caps 90 caps vitamina mineral vitamina'),
('10494','quitosana spirulina psyllium b1 e cromo 600mg muwiz quitosana spirulina psyllium b1 e cromo 600mg 120 caps 120 caps vitamina mineral vitamina'),
('10492','vitamina d + k2 em gotas muwiz vitamina d + k2 em gotas 30ml 30ml vitamina mineral vitd'),
('10490','vitamina do complexo b 500mg muwiz vitamina do complexo b 500mg 60 caps 60 caps vitamina mineral vitd'),
('10488','mw vision plus 500mg muwiz mw vision plus 500mg 30 caps 30 caps vitamina mineral vitamina'),
('10359','go cramp block atlhetica nutrition go cramp block 60 caps 60 caps vitamina mineral vitamina'),
('6341','curcumin cleanlab curcumin 60 caps 60 caps vitamina mineral vitamina'),
('6166','multivitaminico e minerais elements of life a z atlhetica nutrition multivitaminico e minerais elements of life a z 60 caps 60 caps vitamina mineral multi'),
('5811','chromium picolinate 250mcg atlhetica nutrition chromium picolinate 250mcg 60 caps 60 caps vitamina mineral vitamina'),
('5795','go repor salt atlhetica nutrition go repor salt 30 caps 30 caps vitamina mineral vitamina'),
('3344','vita d3 + k2 vitafor vita d3 + k2 20ml menta menta 20ml vitamina mineral vitd'),
('3224','vitamina d3 em gotas 2.000ui vitafor vitamina d3 em gotas 2.000ui 10ml 10ml vitamina mineral vitd'),
('1762','vitamina c + zinco ta suplementos vitamina c + zinco 60 caps 60 caps vitamina mineral vitamina'),
('12754','creature demons lab creature pote 300g pote 300g creatina creatina'),
('12740','creatina 100% pure us nutrition creatina 100% pure pote 150g pote 150g creatina creatina'),
('12739','creatina 100% pure us nutrition creatina 100% pure pote 300g pote 300g creatina creatina'),
('12553','energy creatina plus shark pro energy creatina plus pote 300g pote 300g creatina creatina'),
('12501','creatina 7 belo max titanium creatina pote 300g 7 belo pote 300g creatina creatina'),
('12487','creatina monohydratada 100% pura canibal inc creatina monohydratada 100% pura refil 500g refil 500g creatina creatina'),
('12456','powerfuel creatine trustfuel powerfuel creatine 300g 300g creatina creatina'),
('12446','powerfuel creatine trustfuel powerfuel creatine 100g 100g creatina creatina'),
('12421','creatina 100% pure createst30 display 20un saches atlhetica nutrition creatina 100% pure createst30 display 20un saches 5g 5g creatina creatina sache'),
('12420','creatina 100% pure createst30 atlhetica nutrition creatina 100% pure createst30 pote 300g pote 300g creatina creatina'),
('12419','creatina 100% pure createst30 atlhetica nutrition creatina 100% pure createst30 refil 500g refil 500g creatina creatina'),
('12330','creatina vitafor creatina pote 300g pote 300g creatina creatina'),
('12224','creatina creapure max titanium creatina creapure pote 250g pote 250g creatina creapure'),
('11829','creatina probiotica creatina display 30 sticks 5g display 30 sticks 5g creatina creatina sache'),
('9071','creatina atlhetica nutrition creatina 120 caps 120 caps creatina creatina caps'),
('6662','creatina vitafor creatina pote 100g pote 100g creatina creatina'),
('6661','creatina creafort creapure vitafor creatina creafort creapure display 30 saches 3g display 30 saches 3g creatina creapure'),
('6328','creatina atp ta suplementos creatina atp pote 200g pote 200g creatina creatina'),
('5812','creatina 100% pure atlhetica nutrition creatina 100% pure pote 300g pote 300g creatina creatina'),
('5099','creatina shark pro creatina pote 300g natural natural pote 300g creatina creatina'),
('4079','creatina creafort creapure vitafor creatina creafort creapure pote 300g pote 300g creatina creapure'),
('3338','creatina probiotica creatina pote 300g pote 300g creatina creatina'),
('2362','creatina 100% pura ta suplementos creatina 100% pura pote 300g pote 300g creatina creatina'),
('1575','creatina nutrata creatina pote 300g pote 300g creatina creatina'),
('1351','creatina max titanium creatina pote 300g pote 300g creatina creatina'),
('1350','creatina integralmedica creatina pote 300g pote 300g creatina creatina'),
('1348','creatina integralmedica creatina pote 150g pote 150g creatina creatina'),
('12719','creme zero bendu creme zero pote 150g avela dark crunchy avela dark crunchy pote 150g pastas e cremes creme'),
('12718','creme zero bendu creme zero pote 150g avela com cacau avela com cacau pote 150g pastas e cremes creme'),
('12717','creme zero bendu creme zero pote 150g bombom branco bombom branco pote 150g pastas e cremes creme'),
('12196','pasta de amendoim nutrata pasta de amendoim pote 600g leite trufado leite trufado pote 600g pastas e cremes pasta'),
('11948','pasta de amendoim dr. peanut pasta de amendoim pote 400g avela avela pote 400g pastas e cremes pasta'),
('11946','pasta de amendoim dr. peanut pasta de amendoim pote 400g buenissimo buenissimo pote 400g pastas e cremes pasta'),
('11943','pasta de amendoim dr. peanut pasta de amendoim pote 400g leite em po leite em po pote 400g pastas e cremes pasta'),
('11880','pasta de amendoim nutrata pasta de amendoim pote 600g morango morango pote 600g pastas e cremes pasta'),
('11879','pasta de amendoim nutrata pasta de amendoim pote 600g pacoca pacoca pote 600g pastas e cremes pasta'),
('11878','pasta de amendoim nutrata pasta de amendoim pote 600g cookies and cream cookies and cream pote 600g pastas e cremes pasta'),
('11877','pasta de amendoim nutrata pasta de amendoim pote 600g brownie brownie pote 600g pastas e cremes pasta'),
('11876','pasta de amendoim havanna nutrata pasta de amendoim havanna pote 600g dulce de leche crunchy dulce de leche crunchy pote 600g pastas e cremes pasta'),
('11875','pasta de amendoim havanna nutrata pasta de amendoim havanna pote 600g dulce de leche cream dulce de leche cream pote 600g pastas e cremes pasta'),
('11857','creme spread coq10 com whey mrs taste creme spread coq10 com whey pote 160g doce de leite argentino doce de leite argentino pote 160g pastas e cremes creme'),
('11856','creme spread mrs tella coq10 com whey mrs taste creme spread mrs tella coq10 com whey pote 160g creme de avela creme de avela pote 160g pastas e cremes creme'),
('11854','creme spread dubai com whey mrs taste creme spread dubai com whey pote 160g chocolate chocolate pote 160g pastas e cremes creme'),
('11849','creme spread speculoos com whey mrs taste creme spread speculoos com whey pote 160g pote 160g pastas e cremes creme'),
('11617','creme zero bendu creme zero pote 300g pistache pistache pote 300g pastas e cremes creme'),
('11616','creme zero bendu creme zero pote 300g avela bombom branco avela bombom branco pote 300g pastas e cremes creme'),
('11615','creme zero bendu creme zero pote 300g avela com cacau avela com cacau pote 300g pastas e cremes creme'),
('11614','creme zero bendu creme zero pote 300g avela dark crunchy avela dark crunchy pote 300g pastas e cremes creme'),
('10196','pasta de amendoim dr. peanut pasta de amendoim pote 600g banoffee banoffee pote 600g pastas e cremes pasta'),
('9253','pasta de amendoim dr. peanut pasta de amendoim pote 600g beijinho beijinho pote 600g pastas e cremes pasta'),
('6400','pasta de amendoim dr. peanut pasta de amendoim pote 600g bombom italiano bombom italiano pote 600g pastas e cremes pasta'),
('1723','pasta de amendoim dr. peanut pasta de amendoim pote 600g avela avela pote 600g pastas e cremes pasta'),
('1722','pasta de amendoim dr. peanut pasta de amendoim pote 600g cookies & cream cookies e cream pote 600g pastas e cremes pasta'),
('1721','pasta de amendoim dr. peanut pasta de amendoim pote 600g buenissimo buenissimo pote 600g pastas e cremes pasta'),
('1720','pasta de amendoim dr. peanut pasta de amendoim pote 600g leite em po leite em po pote 600g pastas e cremes pasta'),
('12411','carb shark up gel display 10 saches shark pro carb shark up gel display 10 saches 30g acai guarana banana acai guarana banana 30g endurance gel'),
('12406','shark up hidro pro gel display 10 saches shark pro shark up hidro pro gel display 10 saches 20g limao limao 20g endurance gel'),
('12404','shark up free gel display 10 saches shark pro shark up free gel display 10 saches 30g tutti frutti tutti frutti 30g endurance gel'),
('12403','shark up free gel display 10 saches shark pro shark up free gel display 10 saches 30g morango com maracuja morango com maracuja 30g endurance gel'),
('12402','shark up free gel display 10 saches shark pro shark up free gel display 10 saches 30g cola cola 30g endurance gel'),
('12401','shark up free gel display 10 saches shark pro shark up free gel display 10 saches 30g chocolate chocolate 30g endurance gel'),
('12311','saltz 500 z2 z2 foods saltz 500 z2 display 10un 15g frutas vermelhas frutas vermelhas display 10 un 15g endurance sais'),
('12310','saltz 500 z2 z2 foods saltz 500 z2 display 10un 15g agua de coco agua de coco display 10 un 15g endurance sais'),
('12308','bebida energetica em po z2 foods bebida energetica em po display 10un 45g tangerina gelada tangerina gelada display 10 un 45g endurance gel'),
('12307','saltz 500 z2 z2 foods saltz 500 z2 display 10un 7g limao limao display 10 un 7g endurance sais'),
('12306','gel energetico z2+ z2 foods gel energetico z2+ display 10un 25g limao limao display 10 un 25g endurance gel'),
('12305','gel energetico z2+ z2 foods gel energetico z2+ display 10un 25g expresso duplo expresso duplo display 10 un 25g endurance gel'),
('12303','gel energetico z2 z2 foods gel energetico z2 display 10un 25g limonada rosa limonada rosa display 10 un 25g endurance gel'),
('12302','gel energetico z2 z2 foods gel energetico z2 display 10un 25g pitaya pitaya display 10 un 25g endurance gel'),
('12301','gel energetico z2 z2 foods gel energetico z2 display 10un 25g tangerina tangerina display 10 un 25g endurance gel'),
('12300','gel energetico z2 z2 foods gel energetico z2 display 10un 25g frutas tropicais frutas tropicais display 10 un 25g endurance gel'),
('12267','carb up gel super formula display 10 saches probiotica carb up gel super formula display 10 saches 30g chocolate chocolate 30g endurance gel'),
('12239','carb up gel super formula display 10 saches probiotica carb up gel super formula display 10 saches 30g caldo de cana com limao caldo de cana com limao 30g endurance gel'),
('11814','carb up gel black display 10 saches probiotica carb up gel black display 10 saches 30g guarana com acai guarana com acai 30g endurance gel'),
('11812','carb up gel black display 10 saches probiotica carb up gel black display 10 saches 30g laranja laranja 30g endurance gel'),
('11811','carb up gel black display 10 saches probiotica carb up gel black display 10 saches 30g morango morango 30g endurance gel'),
('11810','carb up gel black display 10 saches probiotica carb up gel black display 10 saches 30g caldo de cana com limao caldo de cana com limao 30g endurance gel'),
('5810','go recovery gel atlhetica nutrition go recovery gel display 10 saches 30g morango morango display 10 saches 30g endurance gel'),
('5798','go isotonic drink atlhetica nutrition go isotonic drink saco 900g tangerina tangerina saco 900g endurance isotonico'),
('5796','go isotonic drink atlhetica nutrition go isotonic drink saco 900g lima limao lima limao saco 900g endurance isotonico'),
('2390','go energy now gel atlhetica nutrition go energy now gel display 10 saches 30g morango com limao morango com limao display 10 saches 30g endurance gel'),
('1711','go energy now gel atlhetica nutrition go energy now gel display 10 saches 30g laranja com acerola laranja com acerola display 10 saches 30g endurance gel'),
('12812','thermo cutter slim fullife nutrition thermo cutter slim 210g red ice red ice 210g termogenico termo'),
('12782','thermo cutter slim fullife nutrition thermo cutter slim pote 210g frutas tropicais frutas tropicais pote 210g termogenico termo'),
('12778','cafeina fullflame 200mg fullife nutrition cafeina fullflame 200mg 120 caps 120 caps termogenico cafeina'),
('12777','thermo cutter slim fullife nutrition thermo cutter slim pote 210g abacaxi com hortela abacaxi com hortela pote 210g termogenico termo'),
('12771','thermo cutter slim fullife nutrition thermo cutter slim pote 210g maca maca pote 210g termogenico termo'),
('12770','thermo cutter slim fullife nutrition thermo cutter slim pote 210g melancia melancia pote 210g termogenico termo'),
('12769','thermo cutter slim fullife nutrition thermo cutter slim pote 210g tangerina tangerina pote 210g termogenico termo'),
('12752','psicho killer demons lab psicho killer 60 caps 60 caps termogenico termo'),
('12526','curcuma plus 500mg vitafor curcuma plus 500mg 30 caps 30 caps termogenico termo'),
('12523','termo plus display 30 saches vitafor termo plus display 30 saches 40g frutas vermelhas frutas vermelhas 40g termogenico termo'),
('12522','termo plus vitafor termo plus 240g frutas vermelhas vitafor frutas vermelhas vitafor 240g termogenico termo'),
('12520','v coffee vitafor v coffee pote 220g pote 220g termogenico termo'),
('12268','thermo abdomen bodyaction thermo abdomen 60 caps 60 caps termogenico termo'),
('12109','2hot max titanium 2hot pote 200g tangerina tangerina pote 200g termogenico termo'),
('12107','2hot max titanium 2hot pote 200g limao limao pote 200g termogenico termo'),
('9811','dimethylex under labz dimethylex 60 caps 60 caps termogenico termo'),
('9778','go energy now atlhetica nutrition go energy now 60 caps 60 caps termogenico termo'),
('9028','c4 caffeine free com colina new millen c4 caffeine free com colina pote 220g laranja laranja pote 220g termogenico cafeina'),
('9027','c4 caffeine free com colina new millen c4 caffeine free com colina pote 220g limao limao pote 220g termogenico cafeina'),
('9026','c4 caffeine free com colina new millen c4 caffeine free com colina pote 220g melancia melancia pote 220g termogenico cafeina'),
('8880','hardcore yellow atlhetica nutrition hardcore yellow 90 caps 90 caps termogenico termo'),
('6167','caffeinex 200 atlhetica nutrition caffeinex 200 60 caps 60 caps termogenico cafeina'),
('4081','curcuma plus 500mg vitafor curcuma plus 500mg 60 caps 60 caps termogenico termo'),
('2129','night abdomen bodyaction night abdomen 60 caps 60 caps termogenico termo'),
('1613','lipo burn hd atlhetica nutrition lipo burn hd 60 caps 60 caps termogenico termo'),
('1576','lipo burn hd black atlhetica nutrition lipo burn hd black pote 200g frutas vermelhas frutas vermelhas pote 200g termogenico termo'),
('12722','sticks awe zero display awe sticks awe zero display 14un 50g limonada italiana limonada italiana 50g bebidas energeticos stick'),
('12721','sticks awe zero display awe sticks awe zero display 14un 50g limao & blueberry limao & blueberry 50g bebidas energeticos stick'),
('12720','sticks awe zero display awe sticks awe zero display 14un 50g coco & morango coco & morango 50g bebidas energeticos stick'),
('12563','red bull energy drink red bull red bull energy drink lata 355ml zero zero lata 355ml bebidas energeticos energetico'),
('12265','red bull energy drink red bull red bull energy drink lata 250ml tradicional tradicional lata 250ml bebidas energeticos energetico'),
('12090','bebida awe zero awe bebida awe zero lata 355ml pitaya & lichia pitaya & lichia lata 355ml bebidas energeticos energetico'),
('12089','bebida awe zero awe bebida awe zero lata 355ml morango & kiwi morango & kiwi lata 355ml bebidas energeticos energetico'),
('12088','bebida awe zero awe bebida awe zero lata 355ml limao & gengibre limao & gengibre lata 355ml bebidas energeticos energetico'),
('12087','bebida awe zero awe bebida awe zero lata 355ml citrus citrus lata 355ml bebidas energeticos energetico'),
('11703','agua mineral vila agua mineral 500ml com gas com gas 500ml bebidas energeticos agua'),
('11023','v9 drink shark pro v9 drink lata 269ml limao limao lata 269ml bebidas energeticos energetico'),
('10957','v9 drink shark pro v9 drink lata 269ml energetico energetico lata 269ml bebidas energeticos energetico'),
('10956','v9 drink shark pro v9 drink lata 269ml laranja laranja lata 269ml bebidas energeticos energetico'),
('10471','monster energy monster monster energy lata 473ml zero zero lata 473ml bebidas energeticos energetico'),
('10468','x7 smart the drink atlhetica nutrition x7 smart the drink 473ml ki suco uva ki suco uva 473ml bebidas energeticos energetico'),
('10441','agent orange energy drink new millen agent orange energy drink lata 269ml tangerina com morango tangerina com morango lata 269ml bebidas energeticos energetico'),
('10440','agent orange energy drink new millen agent orange energy drink lata 269ml limao com hortela limao com hortela lata 269ml bebidas energeticos energetico'),
('10147','monster energy monster monster energy lata 473ml original original lata 473ml bebidas energeticos energetico'),
('9245','h2o limoneto h2o h2o limoneto 500ml 500ml bebidas energeticos energetico'),
('9145','x7 smart the drink atlhetica nutrition x7 smart the drink 473ml acai berry acai berry 473ml bebidas energeticos energetico'),
('8877','x7 smart the drink atlhetica nutrition x7 smart the drink 473ml espumante espumante 473ml bebidas energeticos energetico'),
('8876','x7 smart the drink atlhetica nutrition x7 smart the drink 473ml caipirinha caipirinha 473ml bebidas energeticos energetico'),
('8875','x7 smart the drink atlhetica nutrition x7 smart the drink 473ml refresh citrus refresh citrus 473ml bebidas energeticos energetico'),
('6061','agua mineral indaia agua mineral 500ml sem gas sem gas 500ml bebidas energeticos agua'),
('1467','max energy lata framboesa max titanium max energy lata framboesa bebidas energeticos energetico'),
('12632','creajuice shark pro creajuice pote 300g laranja com acerola laranja com acerola pote 300g aminoacidos amino'),
('12551','energy creatina flavour shark pro energy creatina flavour pote 300g uva uva pote 300g aminoacidos amino'),
('12516','nitrato probiotica nitrato pote 220g beterraba com laranja beterraba com laranja pote 220g aminoacidos amino'),
('12455','powerfuel glutamine trustfuel powerfuel glutamine 300g 300g aminoacidos amino'),
('12335','glutamina glutamax vitafor glutamina glutamax display 30 saches 5g display 30 saches 5g aminoacidos glutamina'),
('12253','nac n acetil l cisteina uniao vegetal nac n acetil l cisteina 60 caps 60 caps aminoacidos amino'),
('11740','arginina + boro vitaminlife arginina + boro 60 caps 60 caps aminoacidos arginina'),
('11700','morotim uniao vegetal morotim 450ml laranja com frutas vermelhas laranja com frutas vermelhas 450ml aminoacidos amino'),
('11699','morotim uniao vegetal morotim 450ml maca verde maca verde 450ml aminoacidos amino'),
('11698','morotim uniao vegetal morotim 450ml morango morango 450ml aminoacidos amino'),
('11690','morotim uniao vegetal morotim 450ml uva uva 450ml aminoacidos amino'),
('11675','glutamina diamond ta suplementos glutamina diamond pote 300g pote 300g aminoacidos glutamina'),
('10175','arginina premium aminoboost ta suplementos arginina premium aminoboost 120 tabs 120 caps aminoacidos arginina'),
('10151','glutamina nutrata glutamina pote 300g pote 300g aminoacidos glutamina'),
('8551','l carnitina vitafor l carnitina 120 caps 120 caps aminoacidos carnitina'),
('8547','glutamina glutamax vitafor glutamina glutamax pouch 600g pouch 600g aminoacidos glutamina'),
('7279','l carnitina 2000 + chromium atlhetica nutrition l carnitina 2000 + chromium 480ml uva uva 480ml aminoacidos carnitina'),
('3219','glutamina glutamax vitafor glutamina glutamax pote 300g pote 300g aminoacidos glutamina'),
('2361','beta alanina ta suplementos beta alanina pote 200g pote 200g aminoacidos beta'),
('2360','arginina ta suplementos arginina pote 100g pote 100g aminoacidos arginina'),
('1664','l carnitine 1400 atlhetica nutrition l carnitine 1400 480ml limao limao 480ml aminoacidos carnitina'),
('1631','l carnitine 1400 atlhetica nutrition l carnitine 1400 480ml abacaxi abacaxi 480ml aminoacidos carnitina'),
('1608','beta alanine 100% pure atlhetica nutrition beta alanine 100% pure pote 200g pote 200g aminoacidos beta'),
('12127','calda para sobremesa zero mrs taste calda para sobremesa zero 335g pumpkin spice pumpkin spice 335g molhos e caldas calda'),
('11838','calda para sobremesa zero mrs taste calda para sobremesa zero 335g cookies and cream cookies and cream 335g molhos e caldas calda'),
('9336','molho mrs chicken zero mrs taste molho mrs chicken zero 320g 320g molhos e caldas molho'),
('2358','ketchup zero mrs taste ketchup zero 350g original original 350g molhos e caldas molho'),
('1837','molho wing buffalo zero mrs taste green molho wing buffalo zero 320g 320g molhos e caldas molho'),
('1836','molho ranch zero mrs taste green molho ranch zero 320g 320g molhos e caldas molho'),
('1833','barbecue zero mrs taste barbecue zero 350g original original 350g molhos e caldas molho'),
('1630','molho barbecue zero mrs taste molho barbecue zero 350g picante picante 350g molhos e caldas molho'),
('1628','mostarda zero mrs taste mostarda zero 350g original original 350g molhos e caldas molho'),
('1565','calda para sobremesa zero mrs taste calda para sobremesa zero 335g doce de leite doce de leite 335g molhos e caldas calda'),
('1563','calda para sobremesa zero mrs taste calda para sobremesa zero 335g chocolate chocolate 335g molhos e caldas calda'),
('1562','calda para sobremesa zero mrs taste calda para sobremesa zero 335g chocolate com avela chocolate com avela 335g molhos e caldas calda'),
('1561','calda para sobremesa zero mrs taste calda para sobremesa zero 335g morango morango 335g molhos e caldas calda'),
('1546','molho para salada mrs taste green molho para salada 300ml ervas finas ervas finas 300ml molhos e caldas molho'),
('1544','top taste mrs taste green top taste 320g tomate e goiaba tomate e goiaba 320g molhos e caldas molho'),
('1542','molho para salada mrs taste green molho para salada 300ml cebola & alho cebola & alho 300ml molhos e caldas molho'),
('1541','maionese zero mrs taste maionese zero 335g alho alho 335g molhos e caldas molho'),
('1540','american burguer mrs taste american burguer 340g 340g molhos e caldas molho'),
('1536','ketchup zero mrs taste ketchup zero 350g picante picante 350g molhos e caldas molho'),
('1535','maionese zero mrs taste maionese zero 335g tradicional tradicional 335g molhos e caldas molho'),
('12775','full mass fullife nutrition full mass pouch 3kg chocolate belga chocolate belga pouch 3kg hipercalorico hiper'),
('12774','full mass fullife nutrition full mass pouch 3kg morango morango pouch 3kg hipercalorico hiper'),
('12773','full mass fullife nutrition full mass pouch 3kg baunilha baunilha pouch 3kg hipercalorico hiper'),
('3423','super gainers max titanium super gainers saco 3kg morango morango saco 3kg hipercalorico hiper'),
('3422','super gainers max titanium super gainers saco 3kg chocolate chocolate saco 3kg hipercalorico hiper'),
('3421','super gainers max titanium super gainers saco 3kg baunilha baunilha saco 3kg hipercalorico hiper'),
('2487','mass titanium 17500 zero lactose saco max titanium mass titanium 17500 zero lactose saco 2.4kg chocolate chocolate 2.4kg hipercalorico hiper'),
('2391','mass titanium 17500 zero lactose saco max titanium mass titanium 17500 zero lactose saco 2.4kg morango morango 2.4kg hipercalorico hiper'),
('2337','mass titanium 17500 max titanium mass titanium 17500 saco 3kg leite condensado leite condensado saco 3kg hipercalorico hiper'),
('2144','hard mass 18000 bodyaction hard mass 18000 saco 3kg morango morango saco 3kg hipercalorico hiper'),
('2081','creamass integralmedica creamass refil 3kg cookies cookies refil 3kg hipercalorico hiper'),
('1607','100% hiper mass saco atlhetica nutrition 100% hiper mass saco 2.5kg morango morango 2.5kg hipercalorico hiper'),
('1606','100% hiper mass saco atlhetica nutrition 100% hiper mass saco 2.5kg chocolate chocolate 2.5kg hipercalorico hiper'),
('1365','creamass integralmedica creamass refil 3kg morango morango refil 3kg hipercalorico hiper'),
('1364','creamass integralmedica creamass refil 3kg chocolate chocolate refil 3kg hipercalorico hiper'),
('1363','creamass integralmedica creamass refil 3kg baunilha baunilha refil 3kg hipercalorico hiper'),
('12855','shark isotonic display 10 saches shark pro shark isotonic display 10 saches 34g morango com maracuja morango com maracuja 34g carboidrato isotonico'),
('12854','shark isotonic display 10 saches shark pro shark isotonic display 10 saches 34g acai com guarana acai com guarana 34g carboidrato isotonico'),
('12853','shark isotonic display 10 saches shark pro shark isotonic display 10 saches 34g limao limao 34g carboidrato isotonico'),
('12515','gel 25pro boost display 10 saches probiotica gel 25pro boost display 10 saches 25g caramelo salgado caramelo salgado 25g carboidrato carbo'),
('12514','gel 25pro boost display 10 saches probiotica gel 25pro boost display 10 saches 25g cafe com avela cafe com avela 25g carboidrato carbo'),
('12513','gel 25pro energy display 10 saches probiotica gel 25pro energy display 10 saches 25g chocolate maltado chocolate maltado 25g carboidrato carbo'),
('12512','gel 25pro energy display 10 saches probiotica gel 25pro energy display 10 saches 25g cappuccino cappuccino 25g carboidrato carbo'),
('12511','gel 25pro hidra display 10 saches probiotica gel 25pro hidra display 10 saches 25g uva verde uva verde 25g carboidrato carbo'),
('12510','gel 25pro hidra display 10 saches probiotica gel 25pro hidra display 10 saches 25g melancia melancia 25g carboidrato carbo'),
('12509','eletroup display 10 saches probiotica eletroup display 10 saches 8g limao limao 8g carboidrato isotonico'),
('12508','eletroup display 10 saches probiotica eletroup display 10 saches 8g melancia melancia 8g carboidrato isotonico'),
('12507','eletroup display 10 saches probiotica eletroup display 10 saches 8g morango com maracuja morango com maracuja 8g carboidrato isotonico'),
('12234','mega malto dextrin probiotica mega malto dextrin caixa 1kg morango silvestre morango silvestre caixa 1kg carboidrato malto'),
('12233','mega malto dextrin probiotica mega malto dextrin caixa 1kg laranja laranja caixa 1kg carboidrato malto'),
('12232','mega malto dextrin probiotica mega malto dextrin caixa 1kg guarana com acai guarana com acai caixa 1kg carboidrato malto'),
('9148','palatinose low g.i cleanlab palatinose low g.i pote 450g pote 450g carboidrato palatinose'),
('12779','colageno hidrolisado fullife nutrition colageno hidrolisado 84g 120 caps 120 caps colageno colageno'),
('12376','colagentek vitafor colagentek pote 300g neutro neutro pote 300g colageno colageno'),
('12352','colagentek protein vitafor colagentek protein pote 460g tangerina tangerina pote 460g colageno colageno'),
('10182','colageno shark pro colageno pote 230g cranberry cranberry pote 230g colageno colageno'),
('8559','collagen pure atlhetica nutrition collagen pure pote 210g frutas vermelhas frutas vermelhas pote 210g colageno colageno'),
('8558','collagen pure atlhetica nutrition collagen pure pote 210g maracuja maracuja pote 210g colageno colageno'),
('8550','colagentek protein vitafor colagentek protein pote 460g morango morango pote 460g colageno colageno'),
('8549','colagentek protein vitafor colagentek protein pote 460g neutro neutro pote 460g colageno colageno'),
('3223','colagentek vitafor colagentek pote 300g limao limao pote 300g colageno colageno'),
('3220','colagentek vitafor colagentek pote 300g maca verde maca verde pote 300g colageno colageno'),
('3218','colagentek vitafor colagentek pote 300g tangerina tangerina pote 300g colageno colageno'),
('3217','colagentek vitafor colagentek pote 300g laranja com acerola laranja com acerola pote 300g colageno colageno'),
('2138','colageno acido hialuronico bodyaction colageno acido hialuronico pote 200g abacaxi com hortela abacaxi com hortela pote 200g colageno colageno'),
('1382','colageno colagentek tipo ii vitafor colageno colagentek tipo ii 60 caps 60 caps colageno colageno'),
('12524','enzyfor vitafor enzyfor display 10 saches 3g display 10 saches 3g enzima saude coq10'),
('12424','end energy gel vitafor end energy gel display 12 saches 30g tangerina tangerina display 12 saches 30g enzima saude coq10'),
('12381','end caffeine gel vitafor end caffeine gel display 12 saches 30g chocolate belga chocolate belga display 12 saches 30g enzima saude coq10'),
('12354','coenzima q10 100mg vitafor coenzima q10 100mg 60 caps 60 caps enzima saude coq10'),
('12337','end caffeine gel vitafor end caffeine gel display 12 saches 30g limao limao display 12 saches 30g enzima saude coq10'),
('12336','end caffeine gel vitafor end caffeine gel display 12 saches 30g mocha mocha display 12 saches 30g enzima saude coq10'),
('12283','coq10 coenzima 200mg under labz coq10 coenzima 200mg 60 caps 60 caps enzima saude coq10'),
('10511','lactase 400mg muwiz lactase 400mg 60 caps 60 caps enzima saude lactase'),
('6351','coenzima coq10 200mg cleanlab coenzima coq10 200mg 60 caps 60 caps enzima saude coq10'),
('1340','coenzima q10 200mg vitafor coenzima q10 200mg 60 caps 60 caps enzima saude coq10'),
('10154','omega 3 1000mg nutrata omega 3 1000mg 60 caps 60 caps omega oleos omega'),
('10153','omega 3 ultra tg 1830mg nutrata omega 3 ultra tg 1830mg 60 caps 60 caps omega oleos omega'),
('10152','omega 3 ultra tg 1830mg nutrata omega 3 ultra tg 1830mg 120 caps 120 caps omega oleos omega'),
('3222','omegafor plus 1000mg vitafor omegafor plus 1000mg 120 caps 120 caps omega oleos omega'),
('3221','omegafor plus 1000mg vitafor omegafor plus 1000mg 60 caps 60 caps omega oleos omega'),
('1373','omega 3 epa dha 1000mg vitafor omega 3 epa dha 1000mg 60 caps 60 caps omega oleos omega'),
('1361','omega 3 epa dha 1000mg vitafor omega 3 epa dha 1000mg 120 caps 120 caps omega oleos omega'),
('11738','curcuma vitaminlife curcuma 60 caps 60 caps sono imunidade sono imunidade'),
('1495','curcu+ curcuma propolis e gengibre uniao vegetal curcu+ curcuma propolis e gengibre 30ml 30ml sono imunidade sono imunidade'),
('11743','long jack thermo uniao vegetal long jack thermo 450ml maca verde maca verde 450ml vasodilatador vasodilatador'),
('11707','long jack thermo uniao vegetal long jack thermo 450ml tangerina tangerina 450ml vasodilatador vasodilatador'),
('10522','cafe verde 500mg muwiz cafe verde 500mg 60 caps 60 caps natural natural'),
('10507','maca peruana 100% puro muwiz maca peruana 100% puro pote 150g pote 150g precursor precursor')
) as v(cod_forn, busca)
where p.cod_forn = v.cod_forn;

-- SKU novo que entrar sem busca preenchida ainda aparece pelo nome
update produto set busca = lower(nome || ' ' || marca) where busca is null;

create index if not exists produto_busca_trgm_idx
  on produto using gin (busca gin_trgm_ops);

-- ---------------------------------------------------------------------
-- vitrine ganha `busca`: o texto de TODOS os SKUs do grupo junto, para que
-- procurar por "chocolate" ache a linha inteira e nao so o SKU de chocolate.
-- ---------------------------------------------------------------------
drop view if exists vitrine;

create view vitrine as
select distinct on (p.grupo)
       p.grupo,
       p.id, p.slug, p.nome, p.linha, p.marca, p.categoria, p.familia,
       p.sabor, p.tamanho, p.foto, p.disponibilidade,
       p.preco_venda_cents, p.preco_referencia_cents,
       g.preco_max_cents,
       g.qtd_sabores, g.qtd_tamanhos, g.qtd_variacoes,
       g.busca
from produto p
join (
  select grupo,
         max(preco_venda_cents)                            as preco_max_cents,
         count(distinct sabor)   filter (where sabor   is not null) as qtd_sabores,
         count(distinct tamanho) filter (where tamanho is not null) as qtd_tamanhos,
         count(*)                                          as qtd_variacoes,
         string_agg(distinct busca, ' ')                    as busca
  from produto where ativo group by grupo
) g on g.grupo = p.grupo
where p.ativo
order by p.grupo, p.preco_venda_cents asc, p.id;

grant select on vitrine to anon, authenticated;

commit;

-- ---------------------------------------------------------------------
-- conferencia
-- ---------------------------------------------------------------------
select 'sem texto de busca' as o, count(*)::text as r from produto where ativo and busca is null
union all select 'acha "proteina"',  count(*)::text from vitrine where busca like '%proteina%'
union all select 'acha "creatina"',  count(*)::text from vitrine where busca like '%creatina%'
union all select 'acha "chocolate"', count(*)::text from vitrine where busca like '%chocolate%'
union all select 'custo exposto?',
       case when has_column_privilege('anon','produto','custo_ne_cents','select')
            then 'FALHOU' else 'OK' end;
